<?php
/**
*
* This file is part of the phpBB Forum Software package.
*
* @copyright (c) phpBB Limited <https://www.phpbb.com>
* @license GNU General Public License, version 2 (GPL-2.0)
*
* For full copyright and license information, please see
* the docs/CREDITS.txt file.
*
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine
//
// Some characters you may want to copy&paste:
// ’ » “ ” …
//

$lang = array_merge($lang, array(
	'TRANSLATION_INFO'	=> '',
	'DIRECTION'			=> 'ltr',
	'DATE_FORMAT'		=> '|Y-M-d|',	// 01 Jan 2007 (with Relative days enabled)
	'DATETIME_FORMAT'	=> '|Y-M-d, H:i|',	// 01 Jan 2007, 13:37 (with Relative days enabled)
	'USER_LANG'			=> 'lt-lt',

	// You can define different rules for the determination of plural forms here.
	// See https://area51.phpbb.com/docs/dev/32x/language/plurals.html for more information
	// or ask the translation manager for help.
	'PLURAL_RULE'		=> 1,

	'1_DAY'			=> '1 dienos',
	'1_MONTH'		=> '1 mėnesio',
	'1_YEAR'		=> '1 metų',
	'2_WEEKS'		=> '2 savaičių',
	'3_MONTHS'		=> '3 mėnesių',
	'6_MONTHS'		=> '6 mėnesių',
	'7_DAYS'		=> '7 dienų',

	'ACCOUNT_ALREADY_ACTIVATED'	=> 'Jūsų vartotojo vardas jau aktyvuotas.',
	'ACCOUNT_DEACTIVATED'	=> 'Jūsų vartotojo vardas buvo išjungtas ir tik administratorius gali jį įjungti.',
	'ACP'	=> 'Administratoriaus valdymo pultas',
	'ACP_SHORT'						=> 'AVP',
	'ACTIVE'	=> 'aktyvus',
	'ACTIVE_ERROR'	=> 'Šis vartotojo vardas yra neaktyvus. Jeigu turite bėdų aktyvuodami savo vartotojo vardą, kreipkitės į diskusijų lentos administratorių.',
	'ADMINISTRATOR'	=> 'Administratorius',
	'ADMINISTRATORS'	=> 'Administratoriai',
	'AGE'	=> 'Amžius',
	'AIM'	=> 'AIM',
	'AJAX_ERROR_TITLE'				=> 'AJAX error',
	'AJAX_ERROR_TEXT'				=> 'Something went wrong when processing your request.',
	'AJAX_ERROR_TEXT_ABORT'			=> 'User aborted request.',
	'AJAX_ERROR_TEXT_TIMEOUT'		=> 'Your request timed out; please try again.',
	'AJAX_ERROR_TEXT_PARSERERROR'	=> 'Something went wrong with the request and the server returned an invalid reply.',	
	'ALLOWED'						=> 'Leidžiama',
	'ALL_FILES'						=> 'Visi failai',
	'ALL_FORUMS'					=> 'Visi forumai',
	'ALL_MESSAGES'					=> 'Visos žinutės',
	'ALL_POSTS'						=> 'Visi pranešimai',
	'ALL_TIMES'						=> 'Visos datos yra <span title="%2$s">%1$s</span>',
	'ALL_TOPICS'					=> 'Visos temos',
	'ALT_TEXT'						=> 'Alternatyvus tekstas',
	'AND'	=> 'ir',
	'ARE_WATCHING_FORUM'	=> 'Jūs užsisakėte gauti perspėjimus apie naujus pranešimus šiame forume.',
	'ARE_WATCHING_TOPIC'	=> 'Jūs užsisakėte gauti perspėjimus apie naujus pranešimus šioje temoje.',
	'ASCENDING'	=> 'Didėjančia tvarka',
	'ATTACHMENTS'	=> 'Prikabinti failai',
	'ATTACHED_IMAGE_NOT_IMAGE'	=> 'Paveikslėlis kurį bandėte prikabinti yra netinkamas.',
	'AUTHOR'	=> 'Autorius',
	'AUTH_NO_PROFILE_CREATED'	=> 'Nepavyko sukurti vartotojo aprašymo.',
	'AUTH_PROVIDER_OAUTH_ERROR_INVALID_ENTRY'				=> 'Invalid database entry.',
	'AUTH_PROVIDER_OAUTH_ERROR_INVALID_SERVICE_TYPE'		=> 'Invalid service type provided to OAuth service handler.',
	'AUTH_PROVIDER_OAUTH_ERROR_SERVICE_NOT_CREATED'			=> 'OAuth service not created',
	'AUTH_PROVIDER_OAUTH_SERVICE_BITLY'						=> 'Bitly',
	'AUTH_PROVIDER_OAUTH_SERVICE_FACEBOOK'					=> 'Facebook',
	'AUTH_PROVIDER_OAUTH_SERVICE_GOOGLE'					=> 'Google',
	'AUTH_PROVIDER_OAUTH_SERVICE_TWITTER'					=> 'Twitter',
	'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_NOT_STORED'			=> 'OAuth token not stored.',
	'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_INCORRECTLY_STORED'	=> 'OAuth token incorrectly stored.',	
	'AVATAR_DISALLOWED_CONTENT'	=> 'Siuntimas nutrūko, kadangi siunčiamas failas yra kenkėjiškas.',
	'AVATAR_DISALLOWED_EXTENSION'	=> 'Šis failas negali būti rodomas, kadangi išplėtimas <strong>%s</strong> yra neleistinas.',
	'AVATAR_EMPTY_REMOTE_DATA'	=> 'Šis avataras nebuvo įkeltas, kadangi yra netinkamas arba sugadintas.',
	'AVATAR_EMPTY_FILEUPLOAD'	=> 'Įkelto avataro failas yra tuščias.',
	'AVATAR_INVALID_FILENAME'	=> 'Failo pavadinimas %s yra netinkamas.',
	'AVATAR_NOT_UPLOADED'	=> 'Avataras neįkeltas.',
	'AVATAR_NO_TEMP_DIR'			=> 'Temporary folder could not be found or is not writable.',
	'AVATAR_NO_SIZE'	=> 'Nepavyko nustatyti nutolusio avataro pločio ir aukščio. Įveskite juos patys.',
	'AVATAR_PARTIAL_UPLOAD'	=> 'Šis failas buvo tik dalinai įkeltas.',
	'AVATAR_PHP_SIZE_NA'	=> 'Avataro failas per didelis.<br />Nepavyko nustatyti maksimalaus leistino dydžio konfigūraciniame faile php.ini.',
	'AVATAR_PHP_SIZE_OVERRUN'	=> 'Avataro failas per didelis. Maksimalus leistinas įkeliamo failo dydis yra %1$d %2$s.<br />Taip nustatyta konfigūraciniame faile php.ini.',
	'AVATAR_REMOTE_UPLOAD_TIMEOUT'		=> 'The specified avatar could not be uploaded because the request timed out.',
	'AVATAR_PHP_UPLOAD_STOPPED'		=> 'A PHP extension has stopped the file upload.',
	'AVATAR_URL_INVALID'	=> 'Tokio URL adreso nėra.',
	'AVATAR_URL_NOT_FOUND'	=> 'Tokio failo nėra.',
	'AVATAR_WRONG_FILESIZE'	=> 'Avataro failo dydis turi būti tarp 0 ir %1d %2s.',
	'AVATAR_WRONG_SIZE'	=> 'Avataras yra %5$d pikselių pločio ir %6$d pikselių aukščio. Avatarai turi būti bent %1$d pikselių pločio ir %2$d pikselių aukščio, bet ne didesni nei %3$d pikselių pločio ir %4$d pikselių aukščio.',
	
	'BACK_TO_TOP'	=> 'Į viršų',	
	'BACK_TO_PREV'	=> 'Grįžti į ankstesnį puslapį',
	'BAN_TRIGGERED_BY_EMAIL'	=> 'Jūsų el. pašto adresas blokuojamas.',
	'BAN_TRIGGERED_BY_IP'	=> 'Jūsų IP adresas blokuojamas.',
	'BAN_TRIGGERED_BY_USER'	=> 'Jūsų vartotojo vardas blokuojamas.',
	'BBCODE_GUIDE'	=> 'BBKodo gidas',
	'BCC'	=> 'BCC',
	'BIRTHDAYS'	=> 'Gimtadieniai',
	'BOARD_BAN_PERM'	=> 'Jūs buvote užblokuotas <strong>visam laikui</strong>.<br /><br />Norėdami gauti daugiau informacijos susisiekite su %2$sdiskusijų administratoriumi%3$s.',
	'BOARD_BAN_REASON'	=> 'Blokavimo priežastis: <strong>%s</strong>',
	'BOARD_BAN_TIME'	=> 'Jūs buvote užblokuotas iki <strong>%1$s</strong>.<br /><br />Norėdami gauti daugiau informacijos susisiekite su %2$sdiskusijų administratoriumi%3$s.',
	'BOARD_DISABLE'	=> 'Atsiprašome, tačiau diskusijos laikinai nepasiekiamos.',
	'BOARD_DISABLED'	=> 'Diskusijų lenta laikinai išjungta.',
	'BOARD_UNAVAILABLE'	=> 'Atsiprašome, tačiau diskusijos laikinai nepasiekiamos. Pabandykite jungtis po kelių minučių.',
	'BROWSING_FORUM'	=> 'Vartotojai naršantys šį forumą: %1$s',	
	'BROWSING_FORUM_GUESTS'	=> array(
		1	=> 'Vartotojai naršantys šį forumą: %1$s ir %2$d svečias(ių)',
		2	=> 'Vartotojai naršantys šį forumą: %1$s ir %2$d svečių',
	),
	'BUTTON_DELETE'         => 'Ištrinti',	
	'BUTTON_EDIT'			=> 'Redaguoti',
	'BUTTON_FORUM_LOCKED'	=> 'Užrakinta',
	'BUTTON_INFORMATION'    => 'Informacija',	
	'BUTTON_NEW_TOPIC'		=> 'Naujos temos kūrimas',
	'BUTTON_PM'				=> 'AŽ',
	'BUTTON_PM_FORWARD'		=> 'Persiųsti',
	'BUTTON_PM_NEW'			=> 'Nauja AŽ',
	'BUTTON_PM_REPLY'		=> 'Atsakyti',
	'BUTTON_PM_REPLY_ALL'	=> 'Atsakyti visiems',
	'BUTTON_POST_REPLY'		=> 'Skelbti atsakymą',
	'BUTTON_QUOTE'			=> 'Cituoti',
	'BUTTON_REPORT'         => 'Raportuoti',	
	'BUTTON_TOPIC_LOCKED'	=> 'Užrakinta',
	'BUTTON_WARN'           => 'Perspėti',	
	'BYTES'					=> 'Baitai',
	'BYTES_SHORT'			=> 'B',

	'CANCEL'				=> 'Atšaukti',
	'CHANGE'				=> 'Pakeisti',
	'CHANGE_FONT_SIZE'	=> 'Pakeisti šrifto dydį',
	'CHANGING_PREFERENCES'	=> 'Keičiami diskusijų nustatymai',
	'CHANGING_PROFILE'	=> 'Keičiami aprašo nustatymai',
	'CHARACTERS'			=> array(
		1	=> '%d simbolis',
		2	=> '%d simboliai',
	),
	'COLLAPSE_VIEW'			=> 'Suskleisti vaizdą',
	'CLOSE_WINDOW'			=> 'Uždaryti langą',
	'COLOUR_SWATCH'			=> 'Spalvų paletė',
	'COLON'					=> ':',
	'COMMA_SEPARATOR'		=> ', ',	// Comma used to join lists into a single string, use localised comma if appropriate, eg: Ideographic or Arabic
	'CONFIRM'	=> 'Patvirtinti',
	'CONFIRM_CODE'	=> 'Patvirtinimo kodas',
	'CONFIRM_CODE_EXPLAIN'	=> 'Tiksliai įrašykite paveikslėlyje matomą kodą. Didžiosios ir mažosios raidės nesvarbios.',
	'CONFIRM_CODE_WRONG'	=> 'Patvirtinimo kodas kurį įrašėte yra neteisingas.',
	'CONFIRM_OPERATION'	=> 'Ar tikrai norite tęsti operaciją?',
	'CONFIRM_AVATAR_DELETE' => 'Ar tikrai norire ištrinti avatarą?',
	'CONGRATULATIONS'	=> 'Sveikiname',
	'CONNECTION_FAILED'	=> 'Prisijungti nepavyko.',
	'CONNECTION_SUCCESS'	=> 'Prisijungti pavyko!',
	'CONTACT'				=> 'Susisiekti',
	'CONTACT_USER'			=> 'Susisiekti su %s',	
	'CONTACT_US'			=> 'Susisiekite',	
	'COOKIE_CONSENT_INFO'	=> 'Sužinoti daugiau',
	'COOKIE_CONSENT_MSG'	=> 'Šį sveitainė naudoja sausainėlius (angl. cookies) kad jūsų patikrtis šioje svetainėje būtų kuo geriausia.',
	'COOKIE_CONSENT_OK'		=> 'Supratau!',
	'COOKIE_CONSENT_HREF'	=> 'http://cookiesandyou.com',	
	'COOKIES_DELETED'	=> 'Visi diskusijų sausainėliai sėkmingai ištrinti.',
	'CURRENT_TIME'	=> 'Dabar yra %s',

	'DAY'					=> 'Diena',
	'DAYS'					=> 'Dienų',
	'DELETE'				=> 'Ištrinti',
	'DELETE_ALL'			=> 'Ištrinti visus',
	'DELETE_COOKIES'	=> 'Ištrinti sausainėlius',
	'DELETE_MARKED'	=> 'Ištrinti pažymėtus',
	'DELETE_POST'	=> 'Ištrinti pranešimą',
	'DELIMITER'	=> 'Skirtukas',
	'DESCENDING'	=> 'Mažėjančia tvarka',
	'DISABLED'	=> 'Išjungta',
	'DISPLAY'	=> 'Rodyti',
	'DISPLAY_GUESTS'	=> 'Rodyti svečius',
	'DISPLAY_MESSAGES'	=> 'Rodyti paskutines žinutes',
	'DISPLAY_POSTS'	=> 'Rodyti paskutinius pranešimus',
	'DISPLAY_TOPICS'	=> 'Rodyti paskutines temas',
	'DOWNLOADED'	=> 'Atsisiųsta',
	'DOWNLOADING_FILE'	=> 'Failas siunčiamas',
	'DOWNLOAD_COUNTS'		=> array(
		0	=> 'Dar neatsisiųsta',
		1	=> 'Atsisiųsta %d kartą',
		2	=> 'Atsisiųsta %d kartus(ų)',
	),

	'EDIT_POST'	=> 'Redaguoti pranešimą',
	'ELLIPSIS'							=>	'…',
	'EMAIL'	=> 'El. paštas',
	'EMAIL_ADDRESS'	=> 'El. pašto adresas',
	'EMAIL_INVALID_EMAIL'	=> 'El. pašto adresas, kurį įrašėte, yra neteisingas.',
	'EMAIL_SMTP_ERROR_RESPONSE'	=> 'Siunčiant el. paštą <strong>eilutėje %1$s</strong> iškilo problemų. Priežastis: %2$s.',
	'EMPTY_SUBJECT'	=> 'Kurdami naują temą turite įrašyti jos pavadinimą.',
	'TOPIC_UNAPPROVED_FORUM'	=> array(
		1	=> 'Tema laukia patvirtinimo',
		2	=> 'Temos laukia patvirtinimo',
	),	
	'EMPTY_MESSAGE_SUBJECT'	=> 'Rašydami naują žinutę turite nurodyti jos temą.',
	'ENABLED'	=> 'Įjungta',
	'ENCLOSURE'	=> 'Priedas',
	'ENTER_USERNAME'	=> 'Įrašykite vartotojo vardą',
	'ERR_CHANGING_DIRECTORY'	=> 'Pakeisti katalogo nepavyko.',
	'ERR_CONNECTING_SERVER'	=> 'Prisijungti prie serverio nepavyko.',
	'ERR_JAB_AUTH'	=> 'Nepavyko autorizuotis į Jabber serverį.',
	'ERR_JAB_CONNECT'	=> 'Nepavyko prisijungti prie Jabber serverio.',
	'ERR_UNABLE_TO_LOGIN'	=> 'Nurodytas vartotojo vardas arba slaptažodis yra neteisingas.',
	'ERR_UNWATCHING'	=> 'Bandant atsisakyti perspėjimų įvyko klaida.',
	'ERR_WATCHING'	=> 'Bandant užsisakyti perspėjimus įvyko klaida.',
	'ERR_WRONG_PATH_TO_PHPBB'	=> 'Kelias iki phpBB yra netinkamas.',
	'ERROR'									=> 'Klaida',
	'EXPAND_VIEW'						=> 'Išskleisti vaizdą',		
	'EXTENSION'	=> 'Išplėtimas',
	'EXTENSION_DISABLED'				=> 'Išplėtimas <strong>%s</strong> yra išjungtas.',
	'EXTENSION_DISABLED_AFTER_POSTING'	=> 'Išplėtimas <strong>%s</strong> buvo išjungtas ir daugiau neberodomas.',
	'EXTENSION_DOES_NOT_EXIST'			=> 'Išplėtimas <strong>%s</strong> neegzistuoja.',

	'FACEBOOK'				=> 'Facebook',
	'FAQ'	=> 'DUK',
	'FAQ_EXPLAIN'	=> 'Dažnai užduodami klausimai',
	'FEATURE_NOT_AVAILABLE' => 'The requested feature is not available on this board.',
	'FILENAME'	=> 'Failo pavadinimas',
	'FILESIZE'	=> 'Failo dydis',
	'FILEDATE'	=> 'Failo data',
	'FILE_COMMENT'	=> 'Failo aprašymas',
	'FILE_CONTENT_ERR'		=> 'Could not read the contents of file: %s',
	'FILE_JSON_DECODE_ERR'	=> 'Failed to decode json file: %s',	
	'FILE_NOT_FOUND'	=> 'Nepavyko rasti nurodyto failo.',
	'FIND_USERNAME'	=> 'Surasti dalyvį',
	'FOLDER'	=> 'Katalogas',
	'FORGOT_PASS'	=> 'Aš pamiršau savo slaptažodį',
	'FORM_INVALID'	=> 'Jūsų siunčiama forma nebegalioja. Bandykite užpildyti ją dar kartą.',
	'FORUM'	=> 'Forumas',
	'FORUMS'	=> 'Forumai',
	'FORUMS_MARKED'	=> 'Forumai pažymėti kaip perskaityti.',
	'FORUM_CAT'	=> 'Forumo kategorija',
	'FORUM_INDEX'	=> 'Pagrindinis diskusijų puslapis',
	'FORUM_LINK'	=> 'Forumo nuoroda',
	'FORUM_LOCATION'	=> 'Forume',
	'FORUM_LOCKED'	=> 'Forumas užrakintas',
	'FORUM_RULES'	=> 'Forumo taisyklės',
	'FORUM_RULES_LINK'	=> 'Čia galite perskaityti forumo taisykles',
	'FROM'	=> 'iš',
	'FSOCK_DISABLED'	=> 'Operacija neįvykdyta, nes <var>fsockopen</var> funkcija yra išjungta arba nepavyko rasti nurodyto serverio.',
	'FSOCK_TIMEOUT'	=> 'Nepavyko perskaityti tinklo srauto.',
	
	'FTP_FSOCK_HOST'	=> 'FTP serveris',
	'FTP_FSOCK_HOST_EXPLAIN'	=> 'Jūsų FTP serverio vardas.',
	'FTP_FSOCK_PASSWORD'	=> 'FTP slaptažodis',
	'FTP_FSOCK_PASSWORD_EXPLAIN'	=> 'Jūsų FTP vartotojo vardo slaptažodis.',
	'FTP_FSOCK_PORT'	=> 'FTP portas',
	'FTP_FSOCK_PORT_EXPLAIN'	=> 'Portas naudojamas prisijungimui prie jūsų serverio.',
	'FTP_FSOCK_ROOT_PATH'	=> 'Kelias iki phpBB',
	'FTP_FSOCK_ROOT_PATH_EXPLAIN'	=> 'Failų sistemos kelias iki jūsų phpBB diskusijų lentos.',
	'FTP_FSOCK_TIMEOUT'	=> 'Bandymo prisijungti prie FTP laiko limitas',
	'FTP_FSOCK_TIMEOUT_EXPLAIN'	=> 'Laiko tarpas sekundėmis, kurį sistema lauks atsakymo iš jūsų serverio.',
	'FTP_FSOCK_USERNAME'	=> 'FTP vartotojo vardas',
	'FTP_FSOCK_USERNAME_EXPLAIN'	=> 'Jūsų FTP vartotojo vardas.',
	
	'FTP_HOST'	=> 'FTP serveris',
	'FTP_HOST_EXPLAIN'	=> 'Jūsų FTP serverio vardas.',
	'FTP_PASSWORD'	=> 'FTP slaptažodis',
	'FTP_PASSWORD_EXPLAIN'	=> 'Jūsų FTP vartotojo vardo slaptažodis.',
	'FTP_PORT'	=> 'FTP portas',
	'FTP_PORT_EXPLAIN'	=> 'Portas naudojamas prisijungimui prie jūsų serverio.',
	'FTP_ROOT_PATH'	=> 'Kelias iki phpBB',
	'FTP_ROOT_PATH_EXPLAIN'	=> 'Failų sistemos kelias iki jūsų phpBB diskusijų lentos.',
	'FTP_TIMEOUT'	=> 'Bandymo prisijungti prie FTP laiko limitas',
	'FTP_TIMEOUT_EXPLAIN'	=> 'Laiko tarpas sekundėmis, kurį sistema lauks atsakymo iš jūsų serverio.',
	'FTP_USERNAME'	=> 'FTP vartotojo vardas',
	'FTP_USERNAME_EXPLAIN'	=> 'Jūsų FTP vartotojo vardas.',

	'GENERAL_ERROR'	=> 'Pagrindinė klaida',
	'GB'	=> 'GB',
	'GIB'	=> 'GiB',
	'GO'	=> 'Pirmyn',
	'GOOGLEPLUS'				=> 'Google+',	
	'GOTO_FIRST_POST'			=> 'Go to first post',
	'GOTO_LAST_POST'			=> 'Go to last post',	
	'GOTO_PAGE'	=> 'Eiti į',
	'GROUP'	=> 'Grupė',
	'GROUPS'	=> 'Grupės',
	'GROUP_ERR_TYPE'	=> 'Nurodėte netinkamą grupės tipą.',
	'GROUP_ERR_USERNAME'	=> 'Jūs neįrašėte grupės pavadinimo.',
	'GROUP_ERR_USER_LONG'	=> 'Grupės pavadinimas negali būti ilgesnis nei 60 simbolių. Nurodytas grupės pavadinimas yra per ilgas.',
	'GUEST'	=> 'Svečias',
	'GUEST_USERS_ONLINE'		=> array(
		1	=> 'Dabar prisijungęs %d svečias',
		2	=> 'Dabar prisijungę %d svečiai',
	),	
	'GUEST_USERS_TOTAL'			=> array(
		1	=> '%d svečias',
		2	=> '%d svečiai',
	),	
	'G_ADMINISTRATORS'	=> 'Administratoriai',
	'G_BOTS'	=> 'Robotai',
	'G_GUESTS'	=> 'Svečiai',
	'G_REGISTERED'	=> 'Užsiregistravę vartotojai',
	'G_REGISTERED_COPPA'	=> 'Užsiregistravę COPPA vartotojai',
	'G_GLOBAL_MODERATORS'	=> 'Globalūs moderatoriai',
	'G_NEWLY_REGISTERED'	=> 'Naujai registruoti vartotojai',

	'HIDDEN_USERS_ONLINE'		=> array(
		1	=> '%d slaptas vartotojas',
		2	=> '%d slapti(ų) vartotojai(ų)',
	),
	'HIDDEN_USERS_TOTAL'		=> array(
		1	=> '%d slaptas',
		2	=> '%d slapti(ų)',
	),
	'HIDE_GUESTS'					=> 'Paslėpti svečius',
	'HIDE_ME'						=> 'Paslėpti mano būseną šios sesijos metu',
	'HOURS'							=> 'Valandos',
	'HOME'							=> 'Namai',

	'ICQ'	=> 'ICQ',	
	'IF'	=> 'Jeigu',
	'IMAGE'	=> 'Paveikslėlis',
	'IMAGE_FILETYPE_INVALID'	=> 'Paveikslėlio failo išplėtimas %d tipui %s nepalaikomas.',
	'IMAGE_FILETYPE_MISMATCH'	=> 'Nesutampa paveikslėlio tipas: tikėtasi kad failo išplėtimas bus %1$s, tačiau jis buvo %2$s.',
	'IN'	=> 'forume',
	'INACTIVE'					=> 'Nekatyvus',	
	'INDEX'	=> 'Pagrindinis diskusijų puslapis',
	'INFORMATION'	=> 'Informacija',
	'INSECURE_REDIRECT'			=> 'Tried to redirect to potentially insecure url.',	
	'INTERESTS'	=> 'Pomėgiai',
	'INVALID_DIGEST_CHALLENGE'	=> 'Klaida autentifikuojantis.',
	'INVALID_EMAIL_LOG'	=> 'Galbūt <strong>%s</strong> yra neteisingas el. pašto adresas?',
	'INVALID_FEED_ATTACHMENTS'	=> 'The selected feed tried fetching attachments with invalid constraints.',
	'INVALID_PLURAL_RULE'		=> 'The chosen plural rule is invalid. Valid values are integers between 0 and 15.',	
	'IP'	=> 'IP',
	'IP_BLACKLISTED'	=> 'Jūsų IP adresas %1$s buvo užblokuotas, nes patenka į juoduosius sąrašus. Daugiau informacijos rasite <a href="%2$s">%2$s</a> puslapyje.',

	'JABBER'	=> 'Jabber',
	'JOINED'	=> 'Užsiregistravo',
	'JUMP_PAGE'	=> 'Įrašykite puslapio numerį į kurį norite pereiti',
	'JUMP_TO'	=> 'Pereiti į',
	'JUMP_TO_PAGE'	=> 'Norėdami pereiti į puslapį paspauskite čia…',
	'JUMP_TO_PAGE_CLICK'	=> 'Norėdami pereiti į puslapį paspauskite čia',

	'KB'					=> 'KB',
	'KIB'					=> 'KiB',

	'LAST_POST'	=> 'Paskutinis pranešimas',
	'LAST_UPDATED'	=> 'Paskutinį kartą atnaujinta',
	'LAST_VISIT'	=> 'Paskutinis prisijungimas',
	'LDAP_NO_LDAP_EXTENSION'	=> 'Nepavyko rasti LDAP modulio.',
	'LDAP_NO_SERVER_CONNECTION'	=> 'Nepavyko prisijungti prie LDAP serverio.',
	'LDAP_SEARCH_FAILED'	=> 'Ieškant LDAP direktorijoje įvyko klaida.',
	'LEGEND'	=> 'Legenda',
	'LIVE_SEARCHES_NOT_ALLOWED'			=> 'Live searches are not allowed.',	
	'LOADING'							=> 'Kraunasi',	
	'LOCATION'	=> 'Miestas',
	'LOCK_POST'	=> 'Užrakinti pranešimą',
	'LOCK_POST_EXPLAIN'	=> 'Neleisti redaguoti',
	'LOCK_TOPIC'	=> 'Užrakinti temą',
	'LOGIN'	=> 'Prisijungti',
	'LOGIN_CHECK_PM'	=> 'Norėdami peržiūrėti asmenines žinutes prisijunkite.',
	'LOGIN_CONFIRMATION'	=> 'Prisijungimo patvirtinimas',
	'LOGIN_CONFIRM_EXPLAIN'	=> 'Po tam tikro maksimalaus bandymų prisijungti kiekio jūs turite įvesti patvirtinimo kodą. Taip daroma norint užtikrinti jūsų vartotojo vardo saugumą. Kodą turėtumėte matyti paveikslėlyje apačioje. Jeigu blogai matote arba dėl kokių nors kitų priežasčių negalite jo perskaityti susisiekite su %sdiskusijų administratoriumi%s.',
	'LOGIN_ERROR_ATTEMPTS'	=> 'Jūs išnaudojote maksimalų bandymų prisijungti kiekį. Be vartotojo vardo bei slaptažodžio dabar turite išspręsti ir CAPTCHA apačioje.',
	'LOGIN_ERROR_EXTERNAL_AUTH_APACHE'	=> 'Apache serveris jūsų neautentifikavo.',
	'LOGIN_ERROR_OAUTH_SERVICE_DOES_NOT_EXIST'	=> 'A non-existant OAuth service has been requested.',	
	'LOGIN_ERROR_PASSWORD'	=> 'Jūs įvedėte neteisingą slaptažodį. Patikrinkite slaptažodį ir pabandykite dar kartą. Jeigu vis tiek iškyla kokių nors problemų susisiekite su %sdiskusijų administratoriumi%s.',
	'LOGIN_ERROR_PASSWORD_CONVERT'	=> 'Po diskusijų lentos atnaujinimo darbų jūsų slaptažodis nebuvo perkeltas. %sUžsisakykite naują slaptažodį%s. Jeigu vis tiek iškyla kokių nors problemų susisiekite su %sdiskusijų administratoriumi%s.',
	'LOGIN_ERROR_USERNAME'	=> 'Jūs įvedėte neteisingą vartotojo vardą. Patikrinkite slaptažodį ir pabandykite dar kartą. Jeigu vis tiek iškyla kokių nors problemų susisiekite su %sdiskusijų administratoriumi%s.',
	'LOGIN_FORUM'	=> 'Norėdami peržiūrėti arba rašyti į šį forumą turite įrašyti jo slaptažodį.',
	'LOGIN_INFO'	=> 'Norėdami prisijungti turite būti užsiregistravę. Registracija užtrunka vos kelias akimirkas tačiau suteikia jums daugiau galimybių. Diskusijų administratorius gali suteikti papildomas teises registruotiems vartotojams. Prieš užsiregistruodami susipažinkite su naudojimosi sąlygomis ir nuostatomis. Naršydami po diskusijas perskaitykite kiekvieno forumo taisykles.',
	'LOGIN_VIEWFORUM'	=> 'Norėdami peržiūrėti šį forumą turite užsiregistruoti ir prisijungti.',
	'LOGIN_EXPLAIN_EDIT'	=> 'Norėdami redaguoti pranešimus šiame forume turite užsiregistruoti ir prisijungti.',
	'LOGIN_EXPLAIN_VIEWONLINE'	=> 'Norėdami peržiūrėti dabar prisijungusių sąrašą turite užsiregistruoti ir prisijungti.',
	'LOGIN_REQUIRED'					=> 'Prisijunkite norėdami atlikti šį veiksmą.',	
	'LOGOUT'	=> 'Atsijungti',
	'LOGOUT_USER'	=> 'Atsijungti [ %s ]',
	'LOG_ME_IN'	=> 'Prijungti mane automatiškai kiekvieno apsilankymo metu',

	'MAIN'					=> 'Pagrindinis',
	'MARK'	=> 'Pažymėti',
	'MARK_ALL'	=> 'Pažymėti visus',
	'MARK_ALL_READ'			=> 'Pažymėti visus kaip perskaitytus',	
	'MARK_FORUMS_READ'	=> 'Pažymėti visus forumus kaip perskaitytus',
	'MARK_READ'				=> 'Pažymėti kaip perskaitytą',	
	'MARK_SUBFORUMS_READ'	=> 'Pažymėti gilesnius forumus kaip perskaitytus',
	'MB'	=> 'MB',
	'MIB'	=> 'MiB',
	'MCP'	=> 'Moderatoriaus valdymo pultas',
	'MCP_SHORT'				=> 'MVP',	
	'MEMBERLIST'	=> 'Dalyvių sąrašas',
	'MEMBERLIST_EXPLAIN'	=> 'Peržiūrėti visą dalyvių sąrašą',
	'MERGE'	=> 'Sujungti',
	'MERGE_POSTS'	=> 'Perkelti pranešimus',
	'MERGE_TOPIC'	=> 'Sujungti temas',
	'MESSAGE'	=> 'Žinutė',
	'MESSAGES'	=> 'Žinutės',
	'MESSAGES_COUNT'		=> array(
		1	=> '%d žinutė',
		2	=> '%d žinutės',
	),	
	'MESSAGE_BODY'	=> 'Laiško turinys',
	'MINUTES'	=> 'Minučių',
	'MODERATE'	=> 'Moderuoti',
	'MODERATOR'	=> 'Moderatorius',
	'MODERATORS'	=> 'Moderatoriai',
	'MODULE_NOT_ACCESS'		=> 'Module not accessible',
	'MODULE_NOT_FIND'		=> 'Cannot find module %s',
	'MODULE_FILE_INCORRECT_CLASS'	=> 'Module file %s does not contain correct class [%s]',	
	'MONTH'	=> 'Mėnuo',
	'MOVE'	=> 'Perkelti',	

	'NA'						=> 'N/A',
	'NEWEST_USER'				=> 'Naujausias registruotas vartotojas yra <strong>%s</strong>',
	'NEW_MESSAGE'				=> 'Nauja žinutė',
	'NEW_MESSAGES'				=> 'Naujos žinutės',
	'NEW_POST'					=> 'Naujas pranešimas',	// Not used anymore
	'NEW_POSTS'					=> 'Nauji pranešimai',	// Not used anymore
	'NEXT'						=> 'Kitas',		// Used in pagination
	'NEXT_STEP'					=> 'Toliau',
	'NEVER'						=> 'Niekada',
	'NO'						=> 'Ne',
	'NO_NOTIFICATIONS'			=> 'Pranešimų nėra',
	'NOT_ALLOWED_MANAGE_GROUP'	=> 'Jūs neturite teisės keisti šios grupės.',
	'NOT_AUTHORISED'			=> 'Jūs neturite teisės matyti šios srities.',
	'NOT_WATCHING_FORUM'		=> 'Jūs atsisakėte gauti perspėjimus apie naujus pranešimus šiame forume.',
	'NOT_WATCHING_TOPIC'		=> 'Jūs atsisakėte gauti perspėjimus apie naujus pranešimus šioje temoje.',
	'NOTIFICATIONS'				=> 'Pranešimai',
	// This applies for NOTIFICATION_BOOKMARK and NOTIFICATION_POST.
	// %1$s will return a list of users that's concatenated using "," and "and" - see STRING_LIST
	// Once the user count reaches 5 users or more, the list is trimmed using NOTIFICATION_X_OTHERS
	// Once the user count reaches 20 users or more, the list is trimmed using NOTIFICATION_MANY_OTHERS
	// Examples:
	// A replied...
	// A and B replied...
	// A, B and C replied...
	// A, B, C and 2 others replied...
	// A, B, C and others replied...
	'NOTIFICATION_BOOKMARK'				=> array(
		1	=> '<strong>Reply</strong> from %1$s in bookmarked topic:',
	),
	'NOTIFICATION_FORUM'				=> '<em>Forum:</em> %1$s',
	'NOTIFICATION_GROUP_REQUEST'		=> '<strong>Group request</strong> from %1$s to join the group %2$s.',
	'NOTIFICATION_GROUP_REQUEST_APPROVED'	=> '<strong>Group request approved</strong> to join the group %1$s.',
	'NOTIFICATION_METHOD_INVALID'		=> 'The method "%s" does not refer to a valid notification method.',
	'NOTIFICATION_PM'					=> '<strong>Private Message</strong> from %1$s:',
	'NOTIFICATION_POST'					=> array(
		1	=> '<strong>Reply</strong> from %1$s in topic:',
	),
	'NOTIFICATION_POST_APPROVED'		=> '<strong>Post approved</strong>:',
	'NOTIFICATION_POST_DISAPPROVED'		=> '<strong>Post disapproved</strong>:',
	'NOTIFICATION_POST_IN_QUEUE'		=> '<strong>Post approval</strong> request by %1$s:',
	'NOTIFICATION_QUOTE'				=> array(
		1	=> '<strong>Quoted</strong> by %1$s in:',
	),
	'NOTIFICATION_REFERENCE'			=> '"%1$s"',
	'NOTIFICATION_REASON'				=> '<em>Reason:</em> %1$s.',
	'NOTIFICATION_REPORT_PM'			=> '<strong>Private Message reported</strong> by %1$s:',
	'NOTIFICATION_REPORT_POST'			=> '<strong>Post reported</strong> by %1$s:',
	'NOTIFICATION_REPORT_CLOSED'		=> '<strong>Report closed</strong> by %1$s for:',
	'NOTIFICATION_TOPIC'				=> '<strong>New topic</strong> by %1$s:',
	'NOTIFICATION_TOPIC_APPROVED'		=> '<strong>Topic approved</strong>:',
	'NOTIFICATION_TOPIC_DISAPPROVED'	=> '<strong>Topic disapproved</strong>:',
	'NOTIFICATION_TOPIC_IN_QUEUE'		=> '<strong>Topic approval</strong> request by %1$s:',
	'NOTIFICATION_TYPE_NOT_EXIST'		=> 'The notification type "%s" is missing from the file system.',
	'NOTIFICATION_ADMIN_ACTIVATE_USER'	=> '<strong>Activation required</strong> for deactivated or newly registered user: “%1$s”',
	// Used in conjuction with NOTIFICATION_BOOKMARK and NOTIFICATION_POST.
	'NOTIFICATION_MANY_OTHERS'			=> 'others',
	'NOTIFICATION_X_OTHERS'				=> array(
		2	=> '%d others',
	),
	'NOTIFY_ADMIN'	=> 'Praneškite apie tai diskusijų administratoriui.',
	'NOTIFY_ADMIN_EMAIL'	=> 'Praneškite apie tai diskusijų administratoriui: <a href="mailto:%1$s">%1$s</a>',
	'NO_ACCESS_ATTACHMENT'	=> 'Jūs neturite teisės peržiūrėti šio failo.',
	'NO_ACTION'	=> 'Nenurodytas veiksmas.',
	'NO_ADMINISTRATORS'	=> 'Administratorių nėra.',
	'NO_AUTH_ADMIN'	=> 'Priėjimas prie administratoriaus valdymo pulto jums uždraustas, kadangi neturite tam reikalingų teisių.',
	'NO_AUTH_ADMIN_USER_DIFFER'	=> 'Jūs negalite autentifikuotis kaip kitas vartotojas.',
	'NO_AUTH_OPERATION'	=> 'Jūs negalite baigti šios operacijos, nes neturite tam reikalingų teisių.',
	'NO_AVATARS'				=> 'No avatars currently available',	
	'NO_CONNECT_TO_SMTP_HOST'	=> 'Nepavyko prisijungti prie SMTP serverio : %1$s : %2$s',
	'NO_BIRTHDAYS'	=> 'Šiandien gimtadienių nėra',
	'NO_EMAIL_MESSAGE'	=> 'Laiškas tuščias.',
	'NO_EMAIL_RESPONSE_CODE'	=> 'Nepavyko gauti pašto serverio atsakymo kodo.',
	'NO_EMAIL_SUBJECT'	=> 'Nurodykite laiško temą.',
	'NO_FORUM'	=> 'Forumas, kurį pasirinkote, neegzistuoja.',
	'NO_FORUMS'	=> 'Ši diskusijų lenta neturi forumų.',
	'NO_GROUP'	=> 'Grupė, kurią nurodėte, neegzistuoja.',
	'NO_GROUP_MEMBERS'	=> 'Ši grupė neturi narių.',
	'NO_IPS_DEFINED'	=> 'Aprašytų IP adresų arba internetinių vardų nėra',
	'NO_MEMBERS'	=> 'Diskusijų dalyvių, tenkinančių paieškos kriterijus, nėra.',
	'NO_MESSAGES'	=> 'Žinučių nėra',
	'NO_MODE'	=> 'Nenurodytas režimas.',
	'NO_MODERATORS'	=> 'Moderatorių nėra.',
	'NO_NEW_MESSAGES'	=> 'Naujų žinučių nėra',	
	'NO_NEW_POSTS'	=> 'Naujų pranešimų nėra',
	'NO_ONLINE_USERS'	=> 'Registruotų vartotojų nėra',
	'NO_POSTS'	=> 'Pranešimų nėra',
	'NO_POSTS_TIME_FRAME'	=> 'Pasirinktu laiko periodu pranešimų šioje temoje nėra.',
	'NO_FEED_ENABLED'	=> 'Šioje diskusijų lentoje srautų nėra.',
	'NO_FEED'	=> 'Nurodytas srautas neprieinamas.',
	'NO_STYLE_DATA'	=> 'Nepavyko gauti stiliaus duomenų',
	'NO_SUBJECT'	=> 'Nenurodyta tema',
	'NO_SUCH_SEARCH_MODULE'	=> 'Nurodytas paieškos mechanizmas neegzistuoja.',
	'NO_SUPPORTED_AUTH_METHODS'	=> 'Nepavyko rasti nei vieno palaikomo autentifikacijos metodo.',
	'NO_TOPIC'	=> 'Tema, kurią nurodėte, neegzistuoja.',
	'NO_TOPIC_FORUM'	=> 'Tema arba forumas nebeegzistuoja.',
	'NO_TOPICS'	=> 'Šiame forume nėra jokių temų arba pranešimų.',
	'NO_TOPICS_TIME_FRAME'	=> 'Pasirinktu laiko periodu temų šiame forume nėra.',	
	'NO_UNREAD_POSTS'	=> 'Neperskaitytų pranešimų nėra',
	'NO_UPLOAD_FORM_FOUND'	=> 'Įkėlimas pradėtas, tačiau nerasta jokia leistina failų įkėlimo forma.',
	'NO_USER'	=> 'Vartotojas, kurį nurodėte, neegzistuoja.',
	'NO_USERS'	=> 'Vartotojai, kurį nurodėte, neegzistuoja.',
	'NO_USER_SPECIFIED'	=> 'Nenurodėte vartotojo vardo.',

	// Nullar/Singular/Plural language entry. The key numbers define the number range in which a certain grammatical expression is valid.
	'NUM_ATTACHMENTS'		=> array(
		1	=> '%d prikabintas failas',
		2	=> '%d prikabinti failai',
	),
	'NUM_POSTS_IN_QUEUE'		=> array(
		0			=> 'Pranešimų eilėje nėra',		// 0
		1			=> 'Eilėje 1 pranešimas',		// 1
		2			=> 'Eilėje %d pranešimai(ų)',		// 2+
	),

	'OCCUPATION'	=> 'Pareigos',
	'OFFLINE'	=> 'Atsijungęs',
	'ONLINE'	=> 'Prisijungęs',
	'ONLINE_BUDDIES'	=> 'Prisijungę draugai',
	// "... :: x registered and y hidden"
	'ONLINE_USERS_TOTAL'		=> array(
		1	=> 'Iš viso šiuo metu prisijungę <strong>%1$d</strong> vartotojas :: %2$s ir %3$s',
		2	=> 'Iš viso šiuo metu prisijungę <strong>%1$d</strong> vartotojų :: %2$s ir %3$s',
	),
	// "... :: x registered, y hidden and z guests"
	'ONLINE_USERS_TOTAL_GUESTS'	=> array(
		1	=> 'Iš viso šiuo metu prisijungę <strong>%1$d</strong> vartotojas :: %2$s, %3$s ir %4$s',
		2	=> 'Iš viso šiuo metu prisijungę <strong>%1$d</strong> vartotojų :: %2$s, %3$s ir %4$s',
	),
	'OPTIONS'					=> 'Nustatymai',

	'PAGE_NOT_FOUND'		=> 'Puslapis nerastas.',
	'PAGE_OF'				=> 'Puslapis <strong>%1$d</strong> iš <strong>%2$d</strong>',
	'PAGE_TITLE_NUMBER'		=> 'Puslapis %s',
	'PASSWORD'				=> 'Slaptažodis',
	'PIXEL'					=> 'px',
	'PIXELS'				=> array(
		1	=> '%d pixel',
		2	=> '%d pixels',
	),
	'PLEASE_WAIT'			=> 'Prašau palaukti.',
	'PM'					=> 'AŽ',
	'PM_REPORTED'	=> 'Peržiūrėti raportą',
	'POSTING_MESSAGE'	=> 'Rašo pranešimą forume %s',
	'POSTING_PRIVATE_MESSAGE'	=> 'Rašo asmeninę žinutę',
	'POST'	=> 'Standartinė',
	'POST_ANNOUNCEMENT'	=> 'Svarbi!',
	'POST_STICKY'	=> 'Dažna',
	'POSTED'	=> 'Parašytas',
	'POSTED_IN_FORUM'	=> 'forume',
	'POSTED_ON_DATE'	=> '',
	'POSTS'	=> 'Pranešimai',
	'POSTS_UNAPPROVED'	=> 'Šioje temoje yra mažiausiai vienas nepatvirtintas pranešimas.',
	'POSTS_UNAPPROVED_FORUM'=> 'Šioje temoje yra mažiausiai vienas nepatvirtintas pranešimas.',	
	'POST_BY_AUTHOR'	=> '',
	'POST_BY_FOE'	=> 'Šį pranešimą parašė <strong>%1$s</strong>, kuris šiuo metu yra jūsų priešų sąraše. %2$sRodyti šį pranešimą%3$s.',
	'POST_DISPLAY'			=> '%1$sRodyti iš pranešimą%2$s.',	
	'POST_DAY'	=> '%.2f pranešimų per dieną',
	'POST_DELETED_ACTION'	=> 'Ištrinti pranešimą:',	
	'POST_DELETED'			=> 'Pranešimas ištrintas.',
	'POST_DELETED_BY'		=> '<strong>%2$s</strong> deleted the post by <strong>%1$s</strong> on %3$s.',
	'POST_DELETED_BY_REASON'=> '<strong>%2$s</strong> deleted the post by <strong>%1$s</strong> on %3$s for the following reason: %4$s',	
	'POST_DETAILS'	=> 'Detalus pranešimo aprašymas',
	'POST_NEW_TOPIC'	=> 'Naujos temos kūrimas',
	'POST_PCT'	=> '%.2f%% visų pranešimų',
	'POST_PCT_ACTIVE'	=> '%.2f%% visų vartotojo pranešimų',
	'POST_PCT_ACTIVE_OWN'	=> '%.2f%% visų tavo pranešimų',
	'POST_REPLY'	=> 'Atsakymo rašymas',
	'POST_REPORTED'	=> 'Perskaityti raportą',
	'POST_SUBJECT'	=> 'Pranešimo tema',
	'POST_TIME'	=> 'Pranešimo datą',
	'POST_TOPIC'	=> 'Naujos temos kūrimas',
	'POST_UNAPPROVED_ACTION'	=> 'Pranešimas laukia patvirtinimo:',	
	'POST_UNAPPROVED'	=> 'Šis pranešimas laukia patvirtinimo',
	'POWERED_BY'	=> 'Veikia su %s',
	'PREVIEW'	=> 'Peržiūrėti',
	'PREVIOUS'	=> 'Ankstesnis',
	'PREVIOUS_STEP'	=> 'Atgal',
	'PRIVACY'	=> 'Privatumo politika',
	'PRIVACY_LINK'			=> 'Privatumas',
	'PRIVATE_MESSAGE'	=> 'Asmeninė žinutė',
	'PRIVATE_MESSAGES'	=> 'Asmeninės žinutės',
	'PRIVATE_MESSAGING'	=> 'Asmeninės žinutės',
	'PROFILE'	=> 'Vartotojo valdymo pultas',

	'QUICK_LINKS'			=> 'Nuorodos',

	'RANK'	=> 'Rangas',
	'READING_FORUM'	=> 'Peržiūri temas forume %s',
	'READING_GLOBAL_ANNOUNCE'	=> 'Skaito labai svarbų pranešimą',
	'READING_LINK'	=> 'Lankosi forumo nuorodoje %s',
	'READING_TOPIC'	=> 'Skaito temą forume %s',
	'READ_PROFILE'	=> 'Aprašymas',
	'REASON'	=> 'Priežastis',
	'RECORD_ONLINE_USERS'	=> 'Daugiausia vartotojų (<strong>%1$s</strong>) buvo %2$s',
	'REDIRECT'	=> 'Nuoroda',
	'REDIRECTS'	=> 'Iš viso apsilankymų',
	'REGISTER'	=> 'Registruotis',
	'REGISTERED_USERS'	=> 'Registruoti vartotojai:',
	// "... and 2 hidden users online"
	'REG_USERS_ONLINE'			=> array(
		1	=> 'Dabar prisijungęs %1$d registruotas vartotojas ir %2$s',
		2	=> 'Dabar prisijungę %1$d registruoti vartotojai ir %2$s',
	),
	'REG_USERS_TOTAL'			=> array(
		1	=> '%d registruotas',
		2	=> '%d registruoti',
	),
	'REMOVE'	=> 'Ištrinti',
	'REMOVE_INSTALL'	=> 'Prieš naudodami šią diskusijų lentą ištrinkite, perkelkite arba pervadinkite diegimo (install) katalogą. Kol šis katalogas egzistuoja, bus pasiekiamas tik administratoriaus valdymo pultas.',
	'REPLIES'	=> 'Atsakymai',
	'REPLY_WITH_QUOTE'	=> 'Atsakyti cituojant',
	'REPLYING_GLOBAL_ANNOUNCE'	=> 'Rašo atsakymą į labai svarbų pranešimą',
	'REPLYING_MESSAGE'	=> 'Rašo atsakymą temoje %s',
	'REPORT_BY'	=> 'Raportas',
	'REPORT_POST'	=> 'Raportuoti apie šį pranešimą',
	'REPORTING_POST'	=> 'Raportuoja pranešimą',
	'RESEND_ACTIVATION'	=> 'El. paštu atsisiųsti aktyvavimo kodą',
	'RESET'	=> 'Iš naujo',
	'RESTORE_PERMISSIONS'	=> 'Susigražinti teises',
	'RETURN_INDEX'	=> '%sGrįžti į pagrindinį puslapį%s',
	'RETURN_FORUM'	=> '%sGrįžti į paskutinį aplankytą forumą%s',
	'RETURN_PAGE'	=> '%sGrįžti į praeitą puslapį%s',
	'RETURN_TOPIC'	=> '%sGrįžti į paskutinę aplankytą temą%s',
	'RETURN_TO'	=> 'Grįžti į',
	'RETURN_TO_INDEX'			=> 'Grįžti į pradinį puslapį',	
	'FEED'	=> 'Srautas',
	'FEED_NEWS'	=> 'Naujienos',
	'FEED_TOPICS_ACTIVE'	=> 'Aktyvios temos',
	'FEED_TOPICS_NEW'	=> 'Naujos temos',
	'RULES_ATTACH_CAN'	=> 'Jūs <strong>galite</strong> prikabinti failus šiame forume',
	'RULES_ATTACH_CANNOT'	=> 'Jūs <strong>negalite</strong> prikabinti failų šiame forume',
	'RULES_DELETE_CAN'	=> 'Jūs <strong>galite</strong> ištrinti savo pranešimus šiame forume',
	'RULES_DELETE_CANNOT'	=> 'Jūs <strong>negalite</strong> trinti savo pranešimų šiame forume',
	'RULES_DOWNLOAD_CAN'	=> 'Jūs <strong>galite</strong> atsisiųsti prikabintus failus šiame forume',
	'RULES_DOWNLOAD_CANNOT'	=> 'Jūs <strong>negalite</strong> atsisiųsti prikabintų failų šiame forume',
	'RULES_EDIT_CAN'	=> 'Jūs <strong>galite</strong> redaguoti savo pranešimus šiame forume',
	'RULES_EDIT_CANNOT'	=> 'Jūs <strong>negalite</strong> redaguoti savo pranešimų šiame forume',
	'RULES_LOCK_CAN'	=> 'Jūs <strong>galite</strong> užrakinti savo temas šiame forume',
	'RULES_LOCK_CANNOT'	=> 'Jūs <strong>negalite</strong> užrakinti savo temų šiame forume',
	'RULES_POST_CAN'	=> 'Jūs <strong>galite</strong> kurti naujas temas šiame forume',
	'RULES_POST_CANNOT'	=> 'Jūs <strong>negalite</strong> kurti naujų temų šiame forume',
	'RULES_REPLY_CAN'	=> 'Jūs <strong>galite</strong> atsakinėti į temas šiame forume',
	'RULES_REPLY_CANNOT'	=> 'Jūs <strong>negalite</strong> atsakinėti į temas šiame forume',
	'RULES_VOTE_CAN'	=> 'Jūs <strong>galite</strong> balsuoti šiame forume',
	'RULES_VOTE_CANNOT'	=> 'Jūs <strong>negalite</strong> balsuoti šiame forume',

	'SEARCH'	=> 'Ieškoti',
	'SEARCH_MINI'	=> 'Paieška…',
	'SEARCH_ADV'	=> 'Išplėstinė paieška',
	'SEARCH_ADV_EXPLAIN'	=> 'Rodyti išplėstinės paieškos nustatymus',
	'SEARCH_KEYWORDS'	=> 'Žodžio paieška',
	'SEARCHING_FORUMS'	=> 'Ieško forumuose',
	'SEARCH_ACTIVE_TOPICS'	=> 'Peržiūrėti aktyvias temas',
	'SEARCH_FOR'	=> 'Ieškoti',
	'SEARCH_FORUM'	=> 'Paieška šiame forume…',
	'SEARCH_NEW'	=> 'Peržiūrėti naujus pranešimus',
	'SEARCH_POSTS_BY'	=> 'Ieškoti pranešimų pagal',
	'SEARCH_SELF'	=> 'Peržiūrėti savo pranešimus',
	'SEARCH_TOPIC'	=> 'Paieška šioje temoje…',
	'SEARCH_UNANSWERED'	=> 'Peržiūrėti neatsakytus pranešimus',
	'SEARCH_UNREAD'	=> 'Peržiūrėti neskaitytus pranešimus',
	'SEARCH_USER_POSTS'	=> 'Ieškoti vartotojo pranešimų',
	'SECONDS'	=> 'Sekundžių',
'SEE_ALL'					=> 'Visi',	
	'SELECT'	=> 'Pasirinkti',
	'SELECT_ALL_CODE'	=> 'Pasirinkti visus',
	'SELECT_DESTINATION_FORUM'	=> 'Pasirinkite forumą į kurį norite įkelti',
	'SELECT_FORUM'	=> 'Pasirinkite forumą',
	'SEND_EMAIL'	=> 'Siųsti laišką',
	'SEND_EMAIL_USER'	=> 'Siųsti laišką vartotojui',
	'SEND_PRIVATE_MESSAGE'	=> 'Siųsti asmeninę žinutę',
	'SETTINGS'	=> 'Nustatymai',
	'SIGNATURE'	=> 'Parašas',
	'SKIP'	=> 'Rodyti turinį',
	'SKYPE'						=> 'Skype',	
	'SMTP_NO_AUTH_SUPPORT'	=> 'SMTP serveris nepalaiko autentifikacijos.',
	'SORRY_AUTH_READ'	=> 'Jūs neturite teisės peržiūrėti šio forumo.',
	'SORRY_AUTH_READ_TOPIC'		=> 'You are not authorised to read this topic.',	
	'SORRY_AUTH_VIEW_ATTACH'	=> 'Jūs neturite teisės atsisiųsti šio failo.',
	'SORT_BY'	=> 'Rūšiuoti pagal',
	'SORT_DIRECTION'			=> 'Rūšiavimo kryptis',	
	'SORT_JOINED'	=> 'Registracijos datą',
	'SORT_LOCATION'	=> 'Vietą',
	'SORT_OPTIONS'				=> 'Rodyti rūšiavimo nustatymus',	
	'SORT_RANK'	=> 'Rangą',
	'SORT_POSTS'	=> 'Pranešimų skaičių',
	'SORT_TOPIC_TITLE'	=> 'Temos pavadinimą',
	'SORT_USERNAME'	=> 'Vartotojo vardą',
	'SPLIT_TOPIC'	=> 'Išskirti temą',
	'SQL_ERROR_OCCURRED'	=> 'Įvyko SQL klaida. Jeigu problema pasikartos, susisiekite su %sdiskusijų administratoriumi%s.',
	'STATISTICS'	=> 'Statistika',
	'START_WATCHING_FORUM'	=> 'Užsisakyti forumą',
	'START_WATCHING_TOPIC'	=> 'Užsisakyti temą',
	'STOP_WATCHING_FORUM'	=> 'Atsisakyti forumo',
	'STOP_WATCHING_TOPIC'	=> 'Atsisakyti temos',
	'STRING_LIST_MULTI'			=> '%1$s, ir %2$s',
	'STRING_LIST_SIMPLE'		=> '%1$s ir %2$s',	
	'SUBFORUM'	=> 'Subforumas',
	'SUBFORUMS'	=> 'Subforumai',
	'SUBJECT'	=> 'Pavadinimas',
	'SUBMIT'	=> 'Siųsti',

	'TB'	=> 'TB',
	'TERMS_LINK'		=> 'Sąlygos',	
	'TERMS_USE'	=> 'Naudojimosi sąlygos',
	'TEST_CONNECTION'	=> 'Patikrinti ryšį',
	'THE_TEAM'	=> 'Komanda',
	'TIB'	=> 'TiB',
	'TIME'	=> 'Laikas',
	'TIMEOUT_PROCESSING_REQ'			=> 'Request timed out.',

	'TOO_LARGE'	=> 'Reikšmė, kurią įrašėte, yra per didelė.',
	'TOO_LARGE_MAX_RECIPIENTS'	=> '<strong>Maksimalus asmeninės žinutės gavėjų skaičius</strong> nustatymo reikšmė yra per didelė.',
	
	'TOO_LONG'	=> 'Įrašyta reikšmė yra per ilga.',
		
	'TOO_LONG_CONFIRM_CODE'	=> 'Patvirtinimo kodas yra per ilgas.',
	'TOO_LONG_DATEFORMAT'	=> 'Datos formatas yra per ilgas.',	
	'TOO_LONG_JABBER'	=> 'Jabber vartotojo vardas yra per ilgas.',
	'TOO_LONG_NEW_PASSWORD'	=> 'Slaptažodis yra per ilgas.',	
	'TOO_LONG_PASSWORD_CONFIRM'	=> 'Slaptažodžio patvirtinimas yra per ilgas.',
	'TOO_LONG_USER_PASSWORD'	=> 'Slaptažodis yra per ilgas.',
	'TOO_LONG_USERNAME'	=> 'Vartotojo vardas yra per ilgas.',
	'TOO_LONG_EMAIL'	=> 'El. pašto adresas yra per ilgas.',

	'TOO_MANY_VOTE_OPTIONS'	=> 'Jūs bandėte balsuoti iš karto už keletą atsakymų variantų.',

	'TOO_SHORT'	=> 'Įrašyta reikšmė yra per trumpa.',

	'TOO_SHORT_CONFIRM_CODE'	=> 'Patvirtinimo kodas yra per trumpas.',
	'TOO_SHORT_DATEFORMAT'	=> 'Datos formatas yra per trumpas.',
	'TOO_SHORT_JABBER'	=> 'Jabber vartotojo vardas yra per trumpas.',	
	'TOO_SHORT_NEW_PASSWORD'	=> 'Slaptažodis yra per trumpas.',	
	'TOO_SHORT_PASSWORD_CONFIRM'	=> 'Slaptažodžio patvirtinimas yra per trumpas.',
	'TOO_SHORT_USER_PASSWORD'	=> 'Slaptažodis yra per trumpas.',
	'TOO_SHORT_USERNAME'	=> 'Vartotojo vardas yra per trumpas.',
	'TOO_SHORT_EMAIL'	=> 'El. pašto adresas yra per trumpas.',
	'TOO_SHORT_EMAIL_CONFIRM'	=> 'El. pašto adreso patvirtinimas yra per trumpas.',
	'TOO_SMALL'						=> 'Reikšmė yra per maža.',
	
	'TOO_SMALL_MAX_RECIPIENTS'		=> 'The value of <strong>Maximum number of allowed recipients per private message</strong> setting you entered is too small.',

	'TOPIC'	=> 'Tema',
	'TOPICS'	=> 'Temos',
	'TOPICS_UNAPPROVED'	=> 'Bent viena tema šiame forume nebuvo patvirtinta.',
	'TOPIC_ICON'	=> 'Temos piktograma',
	'TOPIC_LOCKED'	=> 'Ši tema užrakinta, jūs negalite redaguoti pranešimų arba atsakinėti į juos.',
	'TOPIC_LOCKED_SHORT'	=> 'Tema užrakinta',
	'TOPIC_MOVED'	=> 'Tema perkelta',
	'TOPIC_REVIEW'	=> 'Temos peržiūra',
	'TOPIC_TITLE'	=> 'Temos pavadinimas',
	'TOPIC_UNAPPROVED'	=> 'Ši tema dar nepatvirtinta',
	'TOPIC_DELETED'		=> 'Tema ištrinta.',
	'TOTAL_ATTACHMENTS'	=> 'Tema turi prikabintų failų',
	'TOTAL_LOGS'		=> array(
		1	=> '%d įrašas',
		2	=> '%d įrašai(ų)',
	),
	'TOTAL_PMS'		=> array(
		1	=> 'Iš viso %d viena asmeninė žinutė',
		2	=> 'Iš viso %d asmeninės(ių) žinutės(čių)',
	),
	'TOPIC_POLL'		=> 'This topic has a poll.',
	'TOTAL_POSTS'		=> 'Iš viso pranešimų',
	'TOTAL_POSTS_COUNT'	=> array(
		2	=> 'Iš viso <strong>%d</strong> pranešimai(ų)',
	),
	'TOPIC_REPORTED'	=> 'Šioje temoje yra raportuotų pranešimų',
	'TOTAL_TOPICS'		=> array(
		2	=> 'Iš viso <strong>%d</strong> temos(ų)',
	),
	'TOTAL_USERS'		=> array(
		2	=> 'Iš viso <strong>%d</strong> dalyviai(ių)',
	),
	'TRACKED_PHP_ERROR'	=> 'PHP klaidos: %s',
	'TWITTER'			=> 'Twitter',

	'UNABLE_GET_IMAGE_SIZE'	=> 'Nepavyko nustatyti paveikslėlio matmenų.',
	'UNABLE_TO_DELIVER_FILE'	=> 'Failo pristatyti nepavyko.',
	'UNKNOWN_BROWSER'	=> 'Neatpažinta naršyklė',
	'UNMARK_ALL'	=> 'Nepažymėti nieko',
	'UNREAD_MESSAGES'	=> 'Neperskaitytos žinutės',
	'UNREAD_POST'	=> 'Neperskaitytas pranešimas',
	'UNREAD_POSTS'	=> 'Neperskaityti pranešimai',
	'UNWATCH_FORUM_CONFIRM'	=> 'Ar tikrai norite atsisakyti gauti perspėjimus apie naujus pranešimus šiame forume?',
	'UNWATCH_FORUM_DETAILED'	=> 'Ar tikrai norite atsisakyti gauti perspėjimus apie naujus pranešimus forume “%s”?',
	'UNWATCH_TOPIC_CONFIRM'	=> 'Ar tikrai norite atsisakyti gauti perspėjimus apie naujus pranešimus šioje temoje?',
	'UNWATCH_TOPIC_DETAILED'	=> 'Ar tikrai norite atsisakyti gauti perspėjimus apie naujus pranešimus temoje “%s”?',
	'UNWATCHED_FORUMS'	=> 'Jūs atsisakėte gauti perspėjimus apie naujus pranešimus pasirinktuose forumuose.',
	'UNWATCHED_TOPICS'	=> 'Jūs atsisakėte gauti perspėjimus apie naujus pranešimus pasirinktose temose.',
	'UNWATCHED_FORUMS_TOPICS'	=> 'Jūs atsisakėte gauti perspėjimus apie naujus pranešimus pasirinktose temose ir forumuose.',
	'UPDATE'	=> 'Atnaujinti',
	'UPLOAD_IN_PROGRESS'	=> 'Šiuo metu failas siunčiamas.',
	'URL_REDIRECT'	=> 'Jeigu jūsų naršyklė neturi galimybės automatiškai nukreipti į reikiamą puslapį, %spaspauskite ČIA%s.',
	'USERGROUPS'	=> 'Grupės',
	'USERNAME'	=> 'Vartotojo vardas',
	'USERNAMES'	=> 'Vartotojų vardai',
	'USER_AVATAR'	=> 'Vartotojo avataras',
	'USER_CANNOT_READ'	=> 'Jūs negalite skaityti pranešimų šiame forume.',
	'USER_POSTS'			=> array(
		1	=> '%d pranešimas',
		2	=> '%d pranešimai(ų)',
	),	
	'USERS'	=> 'Vartotojai',
	'USE_PERMISSIONS'		=> 'Patikrinti vartotojo teises',

	'USER_NEW_PERMISSION_DISALLOWED'	=> 'Atsiprašome, bet jums neleidžiama naudoti šios galimybės. Galbūt jūs ką tik užsiregistravote ir norėdami naudotis šia galimybe, turite dalyvauti diskusijose kurį laiką.',

	'VARIANT_DATE_SEPARATOR'	=> ' / ',	// Used in date format dropdown, eg: "Today, 13:37 / 01 Jan 2007, 13:37" ... to join a relative date with calendar date
	'VIEWED'	=> 'Peržiūrėta',
	'VIEWED_COUNTS'		=> array(
		0	=> 'Dar neperžiūrėta',
		1	=> 'Peržiūrėta %d kartą',
		2	=> 'Peržiūrėta %d karus(ų)',
	),	
	'VIEWING_CONTACT_ADMIN'		=> 'Viewing contact page',	
	'VIEWING_FAQ'	=> 'Skaito DUK',
	'VIEWING_MEMBERS'	=> 'Peržiūri dalyvio detalų aprašymą',
	'VIEWING_ONLINE'	=> 'Žiūri kas prisijungę',
	'VIEWING_MCP'	=> 'Naudojasi moderatoriaus valdymo pultu',
	'VIEWING_MEMBER_PROFILE'	=> 'Peržiūri dalyvio aprašymą',
	'VIEWING_PRIVATE_MESSAGES'	=> 'Skaito asmenines žinutes',
	'VIEWING_REGISTER'	=> 'Registruojasi',
	'VIEWING_UCP'	=> 'Naudojasi vartotojo valdymo pultu',
	'VIEWS'	=> 'Peržiūrėta',
	'VIEW_BOOKMARKS'	=> 'Peržiūrėti žymes',
	'VIEW_FORUM_LOGS'	=> 'Peržiūrėti forumo įvykių registrą',
	'VIEW_LATEST_POST'	=> 'Peržiūrėti naujausius pranešimus',
	'VIEW_NEWEST_POST'	=> 'Peržiūrėti naujausius neskaitytus pranešimus',
	'VIEW_NOTES'	=> 'Rodyti užrašus apie vartotoją',
	'VIEW_ONLINE_TIMES'			=> array(
		1	=> 'pagal paskutinių %d minučių aktyvumą',
		2	=> 'pagal paskutinių %d minučių aktyvumą',
	),	
	'VIEW_TOPIC'	=> 'Temos rodymas',
	'VIEW_TOPIC_ANNOUNCEMENT'	=> 'Svarbu: ',
	'VIEW_TOPIC_GLOBAL'	=> 'Labai svarbu: ',
	'VIEW_TOPIC_LOCKED'	=> 'Užrakinta: ',
	'VIEW_TOPIC_LOGS'	=> 'Peržiūrėti temos įvykių registrą',
	'VIEW_TOPIC_MOVED'	=> 'Perkelta: ',
	'VIEW_TOPIC_POLL'	=> 'Balsavimas: ',
	'VIEW_TOPIC_STICKY'	=> 'Dažna tema: ',
	'VISIT_WEBSITE'	=> 'Apsilankyti puslapyje',

	'WARNINGS'	=> 'Perspėjimai',
	'WARN_USER'	=> 'Perspėti vartotoją',
	'WATCH_FORUM_CONFIRM'	=> 'Ar tikrai norite užsisakyti gauti perspėjimus apie naujus pranešimus šiame forume?',
	'WATCH_FORUM_DETAILED'	=> 'Ar tikrai norite užsisakyti gauti perspėjimus apie naujus pranešimus forume “%s”?',
	'WATCH_TOPIC_CONFIRM'	=> 'Ar tikrai norite užsisakyti gauti perspėjimus apie naujus pranešimus šioje temoje?',
	'WATCH_TOPIC_DETAILED'	=> 'Ar tikrai norite užsisakyti gauti perspėjimus apie naujus pranešimus temoje “%s”?',
	'WELCOME_SUBJECT'	=> 'Sveiki atvykę į %s diskusijas',
	'WEBSITE'	=> 'Puslapis',
	'WHOIS'	=> 'Informacija apie IP adresą',
	'WHO_IS_ONLINE'	=> 'Dabar prisijungę',
	'WRONG_PASSWORD'	=> 'Jūs įvedėte neteisingą slaptažodį.',
	
	'WRONG_DATA_COLOUR'	=> 'Jūs įvedėte neteisingą spalvos reikšmę.',
	'WRONG_DATA_JABBER'	=> 'Jūs įvedėte neteisingą Jabber vartotojo vardą.',
	'WRONG_DATA_LANG'	=> 'Kalba, kurią pasirinkote, yra netinkama.',
	'WRONG_DATA_POST_SD'		=> 'The post sort direction you specified is not valid.',
	'WRONG_DATA_POST_SK'		=> 'The post sort option you specified is not valid.',
	'WRONG_DATA_TOPIC_SD'		=> 'The topic sort direction you specified is not valid.',
	'WRONG_DATA_TOPIC_SK'		=> 'The topic sort option you specified is not valid.',
	'WROTE'	=> 'rašė',
	

	'YAHOO'				=> 'Yahoo Messenger',
	'YOUTUBE'			=> 'YouTube',
	'YEAR'				=> 'Metai',
	'YEAR_MONTH_DAY'	=> '(YYYY-MM-DD)',
	'YES'				=> 'Taip',
	'YOU_LAST_VISIT'	=> 'Paskutinis prisijungimas: %s',

	'datetime'			=> array(
		'TODAY'		=> 'Šiandien',
		'TOMORROW'	=> 'Rytoj',
		'YESTERDAY'	=> 'Vakar',
		'AGO'		=> array(
			0		=> 'mažiau nei prieš minutę',
			1		=> 'prieš %d minutę',
			2		=> 'prieš %d minutes(čių)',
		),

		'Sunday'	=> 'Sekmadienis',
		'Monday'	=> 'Pirmadienis',
		'Tuesday'	=> 'Antradienis',
		'Wednesday'	=> 'Trečiadienis',
		'Thursday'	=> 'Ketvirtadienis',
		'Friday'	=> 'Penktadienis',
		'Saturday'	=> 'Šeštadienis',

		'Sun'	=> 'Sek',
		'Mon'	=> 'Pir',
		'Tue'	=> 'Ant',
		'Wed'	=> 'Tre',
		'Thu'	=> 'Ket',
		'Fri'	=> 'Pen',
		'Sat'	=> 'Šeš',

		'January'	=> 'Sausis',
		'February'	=> 'Vasaris',
		'March'	=> 'Kovas',
		'April'	=> 'Balandis',
		'May'	=> 'Gegužė',
		'June'	=> 'Birželis',
		'July'	=> 'Liepa',
		'August'	=> 'Rugpjūtis',
		'September'	=> 'Rugsėjis',
		'October'	=> 'Spalis',
		'November'	=> 'Lapkritis',
		'December'	=> 'Gruodis',
		
		'Jan'	=> 'Sau',
		'Feb'	=> 'Vas',
		'Mar'	=> 'Kov',
		'Apr'	=> 'Bal',
		'May_short'	=> 'Geg', // Short representation of "May". May_short used because in English the short and long date are the same for May.
		'Jun'	=> 'Bir',
		'Jul'	=> 'Lie',
		'Aug'	=> 'Rgp',
		'Sep'	=> 'Rgs',
		'Oct'	=> 'Spa',
		'Nov'	=> 'Lap',
		'Dec'	=> 'Gru',		
	),

	// Timezones can be translated. We use this for the Etc/GMT timezones here,
	// because they are named invers to their offset.
	'timezones'		=> array(
		'UTC'					=> 'UTC',
		'UTC_OFFSET'			=> 'UTC%1$s',
		'UTC_OFFSET_CURRENT'	=> 'UTC%1$s - %2$s',

		'Etc/GMT-12'	=> 'UTC+12',
		'Etc/GMT-11'	=> 'UTC+11',
		'Etc/GMT-10'	=> 'UTC+10',
		'Etc/GMT-9'		=> 'UTC+9',
		'Etc/GMT-8'		=> 'UTC+8',
		'Etc/GMT-7'		=> 'UTC+7',
		'Etc/GMT-6'		=> 'UTC+6',
		'Etc/GMT-5'		=> 'UTC+5',
		'Etc/GMT-4'		=> 'UTC+4',
		'Etc/GMT-3'		=> 'UTC+3',
		'Etc/GMT-2'		=> 'UTC+2',
		'Etc/GMT-1'		=> 'UTC+1',
		'Etc/GMT+1'		=> 'UTC-1',
		'Etc/GMT+2'		=> 'UTC-2',
		'Etc/GMT+3'		=> 'UTC-3',
		'Etc/GMT+4'		=> 'UTC-4',
		'Etc/GMT+5'		=> 'UTC-5',
		'Etc/GMT+6'		=> 'UTC-6',
		'Etc/GMT+7'		=> 'UTC-7',
		'Etc/GMT+8'		=> 'UTC-8',
		'Etc/GMT+9'		=> 'UTC-9',
		'Etc/GMT+10'	=> 'UTC-10',
		'Etc/GMT+11'	=> 'UTC-11',
		'Etc/GMT+12'	=> 'UTC-12',

		'Africa/Abidjan'	=> 'Africa/Abidjan',
		'Africa/Accra'		=> 'Africa/Accra',
		'Africa/Addis_Ababa'	=> 'Africa/Addis Ababa',
		'Africa/Algiers'	=> 'Africa/Algiers',
		'Africa/Asmara'		=> 'Africa/Asmara',
		'Africa/Bamako'		=> 'Africa/Bamako',
		'Africa/Bangui'		=> 'Africa/Bangui',
		'Africa/Banjul'		=> 'Africa/Banjul',
		'Africa/Bissau'		=> 'Africa/Bissau',
		'Africa/Blantyre'	=> 'Africa/Blantyre',
		'Africa/Brazzaville'	=> 'Africa/Brazzaville',
		'Africa/Bujumbura'	=> 'Africa/Bujumbura',
		'Africa/Cairo'		=> 'Africa/Cairo',
		'Africa/Casablanca'	=> 'Africa/Casablanca',
		'Africa/Ceuta'		=> 'Africa/Ceuta',
		'Africa/Conakry'	=> 'Africa/Conakry',
		'Africa/Dakar'		=> 'Africa/Dakar',
		'Africa/Dar_es_Salaam'	=> 'Africa/Dar es Salaam',
		'Africa/Djibouti'	=> 'Africa/Djibouti',
		'Africa/Douala'		=> 'Africa/Douala',
		'Africa/El_Aaiun'	=> 'Africa/El Aaiun',
		'Africa/Freetown'	=> 'Africa/Freetown',
		'Africa/Gaborone'	=> 'Africa/Gaborone',
		'Africa/Harare'		=> 'Africa/Harare',
		'Africa/Johannesburg'	=> 'Africa/Johannesburg',
		'Africa/Juba'		=> 'Africa/Juba',
		'Africa/Kampala'	=> 'Africa/Kampala',
		'Africa/Khartoum'	=> 'Africa/Khartoum',
		'Africa/Kigali'		=> 'Africa/Kigali',
		'Africa/Kinshasa'	=> 'Africa/Kinshasa',
		'Africa/Lagos'		=> 'Africa/Lagos',
		'Africa/Libreville'	=> 'Africa/Libreville',
		'Africa/Lome'		=> 'Africa/Lome',
		'Africa/Luanda'		=> 'Africa/Luanda',
		'Africa/Lubumbashi'	=> 'Africa/Lubumbashi',
		'Africa/Lusaka'		=> 'Africa/Lusaka',
		'Africa/Malabo'		=> 'Africa/Malabo',
		'Africa/Maputo'		=> 'Africa/Maputo',
		'Africa/Maseru'		=> 'Africa/Maseru',
		'Africa/Mbabane'	=> 'Africa/Mbabane',
		'Africa/Mogadishu'	=> 'Africa/Mogadishu',
		'Africa/Monrovia'	=> 'Africa/Monrovia',
		'Africa/Nairobi'	=> 'Africa/Nairobi',
		'Africa/Ndjamena'	=> 'Africa/Ndjamena',
		'Africa/Niamey'		=> 'Africa/Niamey',
		'Africa/Nouakchott'	=> 'Africa/Nouakchott',
		'Africa/Ouagadougou'	=> 'Africa/Ouagadougou',
		'Africa/Porto-Novo'	=> 'Africa/Porto-Novo',
		'Africa/Sao_Tome'	=> 'Africa/Sao Tome',
		'Africa/Tripoli'	=> 'Africa/Tripoli',
		'Africa/Tunis'		=> 'Africa/Tunis',
		'Africa/Windhoek'	=> 'Africa/Windhoek',

		'America/Adak'		=> 'America/Adak',
		'America/Anchorage'	=> 'America/Anchorage',
		'America/Anguilla'	=> 'America/Anguilla',
		'America/Antigua'	=> 'America/Antigua',
		'America/Araguaina'	=> 'America/Araguaina',

		'America/Argentina/Buenos_Aires'	=> 'America/Argentina/Buenos Aires',
		'America/Argentina/Catamarca'	=> 'America/Argentina/Catamarca',
		'America/Argentina/Cordoba'		=> 'America/Argentina/Cordoba',
		'America/Argentina/Jujuy'		=> 'America/Argentina/Jujuy',
		'America/Argentina/La_Rioja'	=> 'America/Argentina/La Rioja',
		'America/Argentina/Mendoza'		=> 'America/Argentina/Mendoza',
		'America/Argentina/Rio_Gallegos'	=> 'America/Argentina/Rio Gallegos',
		'America/Argentina/Salta'		=> 'America/Argentina/Salta',
		'America/Argentina/San_Juan'	=> 'America/Argentina/San Juan',
		'America/Argentina/San_Luis'	=> 'America/Argentina/San Luis',
		'America/Argentina/Tucuman'		=> 'America/Argentina/Tucuman',
		'America/Argentina/Ushuaia'		=> 'America/Argentina/Ushuaia',

		'America/Aruba'			=> 'America/Aruba',
		'America/Asuncion'		=> 'America/Asuncion',
		'America/Atikokan'		=> 'America/Atikokan',
		'America/Bahia'			=> 'America/Bahia',
		'America/Bahia_Banderas'	=> 'America/Bahia Banderas',
		'America/Barbados'		=> 'America/Barbados',
		'America/Belem'			=> 'America/Belem',
		'America/Belize'		=> 'America/Belize',
		'America/Blanc-Sablon'	=> 'America/Blanc-Sablon',
		'America/Boa_Vista'		=> 'America/Boa Vista',
		'America/Bogota'		=> 'America/Bogota',
		'America/Boise'			=> 'America/Boise',
		'America/Cambridge_Bay'	=> 'America/Cambridge Bay',
		'America/Campo_Grande'	=> 'America/Campo Grande',
		'America/Cancun'		=> 'America/Cancun',
		'America/Caracas'		=> 'America/Caracas',
		'America/Cayenne'		=> 'America/Cayenne',
		'America/Cayman'		=> 'America/Cayman',
		'America/Chicago'		=> 'America/Chicago',
		'America/Chihuahua'		=> 'America/Chihuahua',
		'America/Costa_Rica'	=> 'America/Costa Rica',
		'America/Creston'		=> 'America/Creston',
		'America/Cuiaba'		=> 'America/Cuiaba',
		'America/Curacao'		=> 'America/Curacao',
		'America/Danmarkshavn'	=> 'America/Danmarkshavn',
		'America/Dawson'		=> 'America/Dawson',
		'America/Dawson_Creek'	=> 'America/Dawson Creek',
		'America/Denver'		=> 'America/Denver',
		'America/Detroit'		=> 'America/Detroit',
		'America/Dominica'		=> 'America/Dominica',
		'America/Edmonton'		=> 'America/Edmonton',
		'America/Eirunepe'		=> 'America/Eirunepe',
		'America/El_Salvador'	=> 'America/El Salvador',
		'America/Fortaleza'		=> 'America/Fortaleza',
		'America/Glace_Bay'		=> 'America/Glace Bay',
		'America/Godthab'		=> 'America/Godthab',
		'America/Goose_Bay'		=> 'America/Goose Bay',
		'America/Grand_Turk'	=> 'America/Grand Turk',
		'America/Grenada'		=> 'America/Grenada',
		'America/Guadeloupe'	=> 'America/Guadeloupe',
		'America/Guatemala'		=> 'America/Guatemala',
		'America/Guayaquil'		=> 'America/Guayaquil',
		'America/Guyana'		=> 'America/Guyana',
		'America/Halifax'		=> 'America/Halifax',
		'America/Havana'		=> 'America/Havana',
		'America/Hermosillo'		=> 'America/Hermosillo',
		'America/Indiana/Indianapolis'	=> 'America/Indiana/Indianapolis',
		'America/Indiana/Knox'		=> 'America/Indiana/Knox',
		'America/Indiana/Marengo'	=> 'America/Indiana/Marengo',
		'America/Indiana/Petersburg'	=> 'America/Indiana/Petersburg',
		'America/Indiana/Tell_City'	=> 'America/Indiana/Tell City',
		'America/Indiana/Vevay'		=> 'America/Indiana/Vevay',
		'America/Indiana/Vincennes'	=> 'America/Indiana/Vincennes',
		'America/Indiana/Winamac'	=> 'America/Indiana/Winamac',
		'America/Inuvik'		=> 'America/Inuvik',
		'America/Iqaluit'		=> 'America/Iqaluit',
		'America/Jamaica'		=> 'America/Jamaica',
		'America/Juneau'		=> 'America/Juneau',
		'America/Kentucky/Louisville'	=> 'America/Kentucky/Louisville',
		'America/Kentucky/Monticello'	=> 'America/Kentucky/Monticello',
		'America/Kralendijk'	=> 'America/Kralendijk',
		'America/La_Paz'		=> 'America/La Paz',
		'America/Lima'			=> 'America/Lima',
		'America/Los_Angeles'	=> 'America/Los Angeles',
		'America/Lower_Princes'	=> 'America/Lower Princes',
		'America/Maceio'		=> 'America/Maceio',
		'America/Managua'		=> 'America/Managua',
		'America/Manaus'		=> 'America/Manaus',
		'America/Marigot'		=> 'America/Marigot',
		'America/Martinique'	=> 'America/Martinique',
		'America/Matamoros'		=> 'America/Matamoros',
		'America/Mazatlan'		=> 'America/Mazatlan',
		'America/Menominee'		=> 'America/Menominee',
		'America/Merida'		=> 'America/Merida',
		'America/Metlakatla'	=> 'America/Metlakatla',
		'America/Mexico_City'	=> 'America/Mexico City',
		'America/Miquelon'		=> 'America/Miquelon',
		'America/Moncton'		=> 'America/Moncton',
		'America/Monterrey'		=> 'America/Monterrey',
		'America/Montevideo'	=> 'America/Montevideo',
		'America/Montreal'		=> 'America/Montreal',
		'America/Montserrat'	=> 'America/Montserrat',
		'America/Nassau'		=> 'America/Nassau',
		'America/New_York'		=> 'America/New York',
		'America/Nipigon'		=> 'America/Nipigon',
		'America/Nome'			=> 'America/Nome',
		'America/Noronha'		=> 'America/Noronha',
		'America/North_Dakota/Beulah'		=> 'America/North Dakota/Beulah',
		'America/North_Dakota/Center'		=> 'America/North Dakota/Center',
		'America/North_Dakota/New_Salem'	=> 'America/North Dakota/New Salem',
		'America/Ojinaga'		=> 'America/Ojinaga',
		'America/Panama'		=> 'America/Panama',
		'America/Pangnirtung'	=> 'America/Pangnirtung',
		'America/Paramaribo'	=> 'America/Paramaribo',
		'America/Phoenix'		=> 'America/Phoenix',
		'America/Port-au-Prince'	=> 'America/Port-au-Prince',
		'America/Port_of_Spain'	=> 'America/Port of Spain',
		'America/Porto_Velho'	=> 'America/Porto Velho',
		'America/Puerto_Rico'	=> 'America/Puerto Rico',
		'America/Rainy_River'	=> 'America/Rainy River',
		'America/Rankin_Inlet'	=> 'America/Rankin Inlet',
		'America/Recife'		=> 'America/Recife',
		'America/Regina'		=> 'America/Regina',
		'America/Resolute'		=> 'America/Resolute',
		'America/Rio_Branco'	=> 'America/Rio Branco',
		'America/Santa_Isabel'	=> 'America/Santa Isabel',
		'America/Santarem'		=> 'America/Santarem',
		'America/Santiago'		=> 'America/Santiago',
		'America/Santo_Domingo'	=> 'America/Santo Domingo',
		'America/Sao_Paulo'		=> 'America/Sao Paulo',
		'America/Scoresbysund'	=> 'America/Scoresbysund',
		'America/Shiprock'		=> 'America/Shiprock',
		'America/Sitka'			=> 'America/Sitka',
		'America/St_Barthelemy'	=> 'America/St. Barthelemy',
		'America/St_Johns'		=> 'America/St. Johns',
		'America/St_Kitts'		=> 'America/St. Kitts',
		'America/St_Lucia'		=> 'America/St. Lucia',
		'America/St_Thomas'		=> 'America/St. Thomas',
		'America/St_Vincent'	=> 'America/St. Vincent',
		'America/Swift_Current'	=> 'America/Swift Current',
		'America/Tegucigalpa'	=> 'America/Tegucigalpa',
		'America/Thule'			=> 'America/Thule',
		'America/Thunder_Bay'	=> 'America/Thunder Bay',
		'America/Tijuana'		=> 'America/Tijuana',
		'America/Toronto'		=> 'America/Toronto',
		'America/Tortola'		=> 'America/Tortola',
		'America/Vancouver'		=> 'America/Vancouver',
		'America/Whitehorse'	=> 'America/Whitehorse',
		'America/Winnipeg'		=> 'America/Winnipeg',
		'America/Yakutat'		=> 'America/Yakutat',
		'America/Yellowknife'	=> 'America/Yellowknife',

		'Antarctica/Casey'		=> 'Antarctica/Casey',
		'Antarctica/Davis'		=> 'Antarctica/Davis',
		'Antarctica/DumontDUrville'	=> 'Antarctica/DumontDUrville',
		'Antarctica/Macquarie'	=> 'Antarctica/Macquarie',
		'Antarctica/Mawson'		=> 'Antarctica/Mawson',
		'Antarctica/McMurdo'	=> 'Antarctica/McMurdo',
		'Antarctica/Palmer'		=> 'Antarctica/Palmer',
		'Antarctica/Rothera'	=> 'Antarctica/Rothera',
		'Antarctica/South_Pole'	=> 'Antarctica/South Pole',
		'Antarctica/Syowa'		=> 'Antarctica/Syowa',
		'Antarctica/Vostok'		=> 'Antarctica/Vostok',

		'Arctic/Longyearbyen'	=> 'Arctic/Longyearbyen',

		'Asia/Aden'			=> 'Asia/Aden',
		'Asia/Almaty'		=> 'Asia/Almaty',
		'Asia/Amman'		=> 'Asia/Amman',
		'Asia/Anadyr'		=> 'Asia/Anadyr',
		'Asia/Aqtau'		=> 'Asia/Aqtau',
		'Asia/Aqtobe'		=> 'Asia/Aqtobe',
		'Asia/Ashgabat'		=> 'Asia/Ashgabat',
		'Asia/Baghdad'		=> 'Asia/Baghdad',
		'Asia/Bahrain'		=> 'Asia/Bahrain',
		'Asia/Baku'			=> 'Asia/Baku',
		'Asia/Bangkok'		=> 'Asia/Bangkok',
		'Asia/Beirut'		=> 'Asia/Beirut',
		'Asia/Bishkek'		=> 'Asia/Bishkek',
		'Asia/Brunei'		=> 'Asia/Brunei',
		'Asia/Choibalsan'	=> 'Asia/Choibalsan',
		'Asia/Chongqing'	=> 'Asia/Chongqing',
		'Asia/Colombo'		=> 'Asia/Colombo',
		'Asia/Damascus'		=> 'Asia/Damascus',
		'Asia/Dhaka'		=> 'Asia/Dhaka',
		'Asia/Dili'			=> 'Asia/Dili',
		'Asia/Dubai'		=> 'Asia/Dubai',
		'Asia/Dushanbe'		=> 'Asia/Dushanbe',
		'Asia/Gaza'			=> 'Asia/Gaza',
		'Asia/Harbin'		=> 'Asia/Harbin',
		'Asia/Hebron'		=> 'Asia/Hebron',
		'Asia/Ho_Chi_Minh'	=> 'Asia/Ho Chi Minh',
		'Asia/Hong_Kong'	=> 'Asia/Hong Kong',
		'Asia/Hovd'			=> 'Asia/Hovd',
		'Asia/Irkutsk'		=> 'Asia/Irkutsk',
		'Asia/Jakarta'		=> 'Asia/Jakarta',
		'Asia/Jayapura'		=> 'Asia/Jayapura',
		'Asia/Jerusalem'	=> 'Asia/Jerusalem',
		'Asia/Kabul'		=> 'Asia/Kabul',
		'Asia/Kamchatka'	=> 'Asia/Kamchatka',
		'Asia/Karachi'		=> 'Asia/Karachi',
		'Asia/Kashgar'		=> 'Asia/Kashgar',
		'Asia/Kathmandu'	=> 'Asia/Kathmandu',
		'Asia/Khandyga'		=> 'Asia/Khandyga',
		'Asia/Kolkata'		=> 'Asia/Kolkata',
		'Asia/Krasnoyarsk'	=> 'Asia/Krasnoyarsk',
		'Asia/Kuala_Lumpur'	=> 'Asia/Kuala Lumpur',
		'Asia/Kuching'		=> 'Asia/Kuching',
		'Asia/Kuwait'		=> 'Asia/Kuwait',
		'Asia/Macau'		=> 'Asia/Macau',
		'Asia/Magadan'		=> 'Asia/Magadan',
		'Asia/Makassar'		=> 'Asia/Makassar',
		'Asia/Manila'		=> 'Asia/Manila',
		'Asia/Muscat'		=> 'Asia/Muscat',
		'Asia/Nicosia'		=> 'Asia/Nicosia',
		'Asia/Novokuznetsk'	=> 'Asia/Novokuznetsk',
		'Asia/Novosibirsk'	=> 'Asia/Novosibirsk',
		'Asia/Omsk'			=> 'Asia/Omsk',
		'Asia/Oral'			=> 'Asia/Oral',
		'Asia/Phnom_Penh'	=> 'Asia/Phnom Penh',
		'Asia/Pontianak'	=> 'Asia/Pontianak',
		'Asia/Pyongyang'	=> 'Asia/Pyongyang',
		'Asia/Qatar'		=> 'Asia/Qatar',
		'Asia/Qyzylorda'	=> 'Asia/Qyzylorda',
		'Asia/Rangoon'		=> 'Asia/Rangoon',
		'Asia/Riyadh'		=> 'Asia/Riyadh',
		'Asia/Sakhalin'		=> 'Asia/Sakhalin',
		'Asia/Samarkand'	=> 'Asia/Samarkand',
		'Asia/Seoul'		=> 'Asia/Seoul',
		'Asia/Shanghai'		=> 'Asia/Shanghai',
		'Asia/Singapore'	=> 'Asia/Singapore',
		'Asia/Taipei'		=> 'Asia/Taipei',
		'Asia/Tashkent'		=> 'Asia/Tashkent',
		'Asia/Tbilisi'		=> 'Asia/Tbilisi',
		'Asia/Tehran'		=> 'Asia/Tehran',
		'Asia/Thimphu'		=> 'Asia/Thimphu',
		'Asia/Tokyo'		=> 'Asia/Tokyo',
		'Asia/Ulaanbaatar'	=> 'Asia/Ulaanbaatar',
		'Asia/Urumqi'		=> 'Asia/Urumqi',
		'Asia/Ust-Nera'		=> 'Asia/Ust-Nera',
		'Asia/Vientiane'	=> 'Asia/Vientiane',
		'Asia/Vladivostok'	=> 'Asia/Vladivostok',
		'Asia/Yakutsk'		=> 'Asia/Yakutsk',
		'Asia/Yekaterinburg'	=> 'Asia/Yekaterinburg',
		'Asia/Yerevan'		=> 'Asia/Yerevan',

		'Atlantic/Azores'		=> 'Atlantic/Azores',
		'Atlantic/Bermuda'		=> 'Atlantic/Bermuda',
		'Atlantic/Canary'		=> 'Atlantic/Canary',
		'Atlantic/Cape_Verde'	=> 'Atlantic/Cape Verde',
		'Atlantic/Faroe'		=> 'Atlantic/Faroe',
		'Atlantic/Madeira'		=> 'Atlantic/Madeira',
		'Atlantic/Reykjavik'	=> 'Atlantic/Reykjavik',
		'Atlantic/South_Georgia'	=> 'Atlantic/South Georgia',
		'Atlantic/St_Helena'	=> 'Atlantic/St. Helena',
		'Atlantic/Stanley'		=> 'Atlantic/Stanley',

		'Australia/Adelaide'	=> 'Australia/Adelaide',
		'Australia/Brisbane'	=> 'Australia/Brisbane',
		'Australia/Broken_Hill'	=> 'Australia/Broken Hill',
		'Australia/Currie'		=> 'Australia/Currie',
		'Australia/Darwin'		=> 'Australia/Darwin',
		'Australia/Eucla'		=> 'Australia/Eucla',
		'Australia/Hobart'		=> 'Australia/Hobart',
		'Australia/Lindeman'	=> 'Australia/Lindeman',
		'Australia/Lord_Howe'	=> 'Australia/Lord Howe',
		'Australia/Melbourne'	=> 'Australia/Melbourne',
		'Australia/Perth'		=> 'Australia/Perth',
		'Australia/Sydney'		=> 'Australia/Sydney',

		'Europe/Amsterdam'	=> 'Europe/Amsterdam',
		'Europe/Andorra'	=> 'Europe/Andorra',
		'Europe/Athens'		=> 'Europe/Athens',
		'Europe/Belgrade'	=> 'Europe/Belgrade',
		'Europe/Berlin'		=> 'Europe/Berlin',
		'Europe/Bratislava'	=> 'Europe/Bratislava',
		'Europe/Brussels'	=> 'Europe/Brussels',
		'Europe/Bucharest'	=> 'Europe/Bucharest',
		'Europe/Budapest'	=> 'Europe/Budapest',
		'Europe/Busingen'	=> 'Europe/Busingen',
		'Europe/Chisinau'	=> 'Europe/Chisinau',
		'Europe/Copenhagen'	=> 'Europe/Copenhagen',
		'Europe/Dublin'		=> 'Europe/Dublin',
		'Europe/Gibraltar'	=> 'Europe/Gibraltar',
		'Europe/Guernsey'	=> 'Europe/Guernsey',
		'Europe/Helsinki'	=> 'Europe/Helsinki',
		'Europe/Isle_of_Man'	=> 'Europe/Isle of Man',
		'Europe/Istanbul'	=> 'Europe/Istanbul',
		'Europe/Jersey'		=> 'Europe/Jersey',
		'Europe/Kaliningrad'	=> 'Europe/Kaliningrad',
		'Europe/Kiev'		=> 'Europe/Kiev',
		'Europe/Lisbon'		=> 'Europe/Lisbon',
		'Europe/Ljubljana'	=> 'Europe/Ljubljana',
		'Europe/London'		=> 'Europe/London',
		'Europe/Luxembourg'	=> 'Europe/Luxembourg',
		'Europe/Madrid'		=> 'Europe/Madrid',
		'Europe/Malta'		=> 'Europe/Malta',
		'Europe/Mariehamn'	=> 'Europe/Mariehamn',
		'Europe/Minsk'		=> 'Europe/Minsk',
		'Europe/Monaco'		=> 'Europe/Monaco',
		'Europe/Moscow'		=> 'Europe/Moscow',
		'Europe/Oslo'		=> 'Europe/Oslo',
		'Europe/Paris'		=> 'Europe/Paris',
		'Europe/Podgorica'	=> 'Europe/Podgorica',
		'Europe/Prague'		=> 'Europe/Prague',
		'Europe/Riga'		=> 'Europe/Riga',
		'Europe/Rome'		=> 'Europe/Rome',
		'Europe/Samara'		=> 'Europe/Samara',
		'Europe/San_Marino'	=> 'Europe/San Marino',
		'Europe/Sarajevo'	=> 'Europe/Sarajevo',
		'Europe/Simferopol'	=> 'Europe/Simferopol',
		'Europe/Skopje'		=> 'Europe/Skopje',
		'Europe/Sofia'		=> 'Europe/Sofia',
		'Europe/Stockholm'	=> 'Europe/Stockholm',
		'Europe/Tallinn'	=> 'Europe/Tallinn',
		'Europe/Tirane'		=> 'Europe/Tirane',
		'Europe/Uzhgorod'	=> 'Europe/Uzhgorod',
		'Europe/Vaduz'		=> 'Europe/Vaduz',
		'Europe/Vatican'	=> 'Europe/Vatican',
		'Europe/Vienna'		=> 'Europe/Vienna',
		'Europe/Vilnius'	=> 'Europe/Vilnius',
		'Europe/Volgograd'	=> 'Europe/Volgograd',
		'Europe/Warsaw'		=> 'Europe/Warsaw',
		'Europe/Zagreb'		=> 'Europe/Zagreb',
		'Europe/Zaporozhye'	=> 'Europe/Zaporozhye',
		'Europe/Zurich'		=> 'Europe/Zurich',

		'Indian/Antananarivo'	=> 'Indian/Antananarivo',
		'Indian/Chagos'		=> 'Indian/Chagos',
		'Indian/Christmas'	=> 'Indian/Christmas',
		'Indian/Cocos'		=> 'Indian/Cocos',
		'Indian/Comoro'		=> 'Indian/Comoro',
		'Indian/Kerguelen'	=> 'Indian/Kerguelen',
		'Indian/Mahe'		=> 'Indian/Mahe',
		'Indian/Maldives'	=> 'Indian/Maldives',
		'Indian/Mauritius'	=> 'Indian/Mauritius',
		'Indian/Mayotte'	=> 'Indian/Mayotte',
		'Indian/Reunion'	=> 'Indian/Reunion',

		'Pacific/Apia'		=> 'Pacific/Apia',
		'Pacific/Auckland'	=> 'Pacific/Auckland',
		'Pacific/Chatham'	=> 'Pacific/Chatham',
		'Pacific/Chuuk'		=> 'Pacific/Chuuk',
		'Pacific/Easter'	=> 'Pacific/Easter',
		'Pacific/Efate'		=> 'Pacific/Efate',
		'Pacific/Enderbury'	=> 'Pacific/Enderbury',
		'Pacific/Fakaofo'	=> 'Pacific/Fakaofo',
		'Pacific/Fiji'		=> 'Pacific/Fiji',
		'Pacific/Funafuti'	=> 'Pacific/Funafuti',
		'Pacific/Galapagos'	=> 'Pacific/Galapagos',
		'Pacific/Gambier'	=> 'Pacific/Gambier',
		'Pacific/Guadalcanal'	=> 'Pacific/Guadalcanal',
		'Pacific/Guam'		=> 'Pacific/Guam',
		'Pacific/Honolulu'	=> 'Pacific/Honolulu',
		'Pacific/Johnston'	=> 'Pacific/Johnston',
		'Pacific/Kiritimati'	=> 'Pacific/Kiritimati',
		'Pacific/Kosrae'	=> 'Pacific/Kosrae',
		'Pacific/Kwajalein'	=> 'Pacific/Kwajalein',
		'Pacific/Majuro'	=> 'Pacific/Majuro',
		'Pacific/Marquesas'	=> 'Pacific/Marquesas',
		'Pacific/Midway'	=> 'Pacific/Midway',
		'Pacific/Nauru'		=> 'Pacific/Nauru',
		'Pacific/Niue'		=> 'Pacific/Niue',
		'Pacific/Norfolk'	=> 'Pacific/Norfolk',
		'Pacific/Noumea'	=> 'Pacific/Noumea',
		'Pacific/Pago_Pago'	=> 'Pacific/Pago Pago',
		'Pacific/Palau'		=> 'Pacific/Palau',
		'Pacific/Pitcairn'	=> 'Pacific/Pitcairn',
		'Pacific/Pohnpei'	=> 'Pacific/Pohnpei',
		'Pacific/Port_Moresby'	=> 'Pacific/Port Moresby',
		'Pacific/Rarotonga'	=> 'Pacific/Rarotonga',
		'Pacific/Saipan'	=> 'Pacific/Saipan',
		'Pacific/Tahiti'	=> 'Pacific/Tahiti',
		'Pacific/Tarawa'	=> 'Pacific/Tarawa',
		'Pacific/Tongatapu'	=> 'Pacific/Tongatapu',
		'Pacific/Wake'		=> 'Pacific/Wake',
		'Pacific/Wallis'	=> 'Pacific/Wallis',
	),

	// The value is only an example and will get replaced by the current time on view
	'dateformats'	=> array(
		'd M Y, H:i'	=> '01 Sau 2007, 13:37',
		'd M Y H:i'	=> '01 Sau 2007 13:37',
		'M jS, \'y, H:i'	=> 'Sau 1st, \'07, 13:37',
		'D M d, Y g:i a'	=> 'Pir Sau 01, 2007 1:37 pm',
		'F jS, Y, g:i a'	=> 'Sausio 1st, 2007, 1:37 pm',
		'|d M Y|, H:i'	=> 'Šiandien, 13:37 / 01 Sau 2007, 13:37',
		'|F jS, Y|, g:i a'	=> 'Šiandien, 1:37 pm / Sausio 1st, 2007, 1:37 pm',
	),

	// The default dateformat which will be used on new installs in this language
	// Translators should change this if a the usual date format is different
	'default_dateformat'	=> 'Y-M-d H:i', // Mon Jan 01, 2007 1:37 pm

));
